### ISSUE TITLE
[intro] Add RTL support

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2015]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1161687](https://bugzilla.mozilla.org/show_bug.cgi?id=1161687)
Bug Reporter: @mathjazz
CC:   @adngdb, @afarsi, h.alshakhori@gmail.com, @jarifibrahim, @yarons

Make Pontoon Intro right-to-left ready:
https://github.com/mathjazz/pontoon-intro

**Comment by mathjazz** [comment]
There's no intro page in Pontoon anymore. We plan to make Pontoon localizable, so we'll add RTL support across the board.
