### ISSUE TITLE
[translate] Move translation validation from view to model

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2018]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1191029](https://bugzilla.mozilla.org/show_bug.cgi?id=1191029)
Bug Reporter: @mathjazz

Refactor pre-translation checks to use Django's built-in validation framework instead of putting all the validation logic in the views.

**Comment by mathjazz** [comment]
I believe this is obsolete as of https://github.com/mozilla/pontoon/pull/1543.
