### ISSUE TITLE
[admin] Add Project Manager role for creating new projects

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2022]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1204659](https://bugzilla.mozilla.org/show_bug.cgi?id=1204659)
Bug Reporter: @Osmose
CC:   ali@alicoding.com, exile@chamber.ee, jm-gailis@fai-vianet.fr, @mathjazz, tblairon@wanadev.fr

In order to better enable groups like mofo to create and edit projects without relying on the Pontoon admin team, we should add a new "Project Manager" role that is allowed to create new projects and edit projects that they've created. 

We can probably handle this by adding per-object permissions (I've used https://github.com/django-guardian/django-guardian in the past with success) limiting the new role to creating new projects. Then, as part of the project creation process, we assign them as an editor of the newly-created project. This'd also open up the ability for Project Managers to assign other users as editors of their projects as well, which may be useful.

This is blocked by our work in bug 1203788 to replace the custom admin interface with the stock Django interface, as we don't want to continue supporting the old admin interface by adding more fields for these improvements.

**Comment by mathjazz** [comment]
The Superuser role has been serving us well for the Project Manager role.
