### ISSUE TITLE
Improve quality checks

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2026]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1221552](https://bugzilla.mozilla.org/show_bug.cgi?id=1221552)
Bug Reporter: @mathjazz
CC:   cgrebs@mozilla.com, felix.bau@gmx.de, mvasicek@mozilla.cz, @tomer, vsatayamas@gmail.com, willkg@mozilla.com, @yfdyh000
Depends on:   [Bug 1224273](https://bugzilla.mozilla.org/show_bug.cgi?id=1224273), [Bug 1376728](https://bugzilla.mozilla.org/show_bug.cgi?id=1376728)

Our quality checks have two issues:

1) There are a lot of false positives.
2) They only show warnings, which users can easily ignore.

Our current implementation uses POfilter tests:
http://translate-toolkit.readthedocs.org/en/latest/commands/pofilter_tests.html

Many Mozilla sites use dennis to prevent bad translations from causing errors in production, so we should look into its API and use it:
https://dennis.readthedocs.org/

We should split tests into different categories by importance (POfilter supports that), something like:

A) COSMETIC: These tests should be removed.
B) WARNING: We show a warning, which can be ignored.
C) ERROR: We prevent translation from being submitted. If detected on import, store it as suggestions.

**Comment by mathjazz** [comment]
Closing on behalf of #2449. There are some other requests in here, feel free to file separate issues if they are still relevant.
