### ISSUE TITLE
Improving profile page

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2028]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1225109](https://bugzilla.mozilla.org/show_bug.cgi?id=1225109)
Bug Reporter: @a-polivanchuk
CC:   drashtipandya37@gmail.com, etrapani@gmail.com, @mathjazz, @MikkCZ, @jotes, safa1996alfulaij@gmail.com
Depends on:   [Bug 1243086](https://bugzilla.mozilla.org/show_bug.cgi?id=1243086), [Bug 1473761](https://bugzilla.mozilla.org/show_bug.cgi?id=1473761)

Currently homepage looks not as good as it could be, especially the contribution history part (vertical timeline).
You have to scroll down for a long time to see the whole history, which also is not very informative.
I think that graph view or even tabbed view of the contribution history would be much better and informative.

**Comment by mathjazz** [comment]
The profile page redesign is now being tracked in a [project](https://github.com/mozilla/pontoon/projects/4).
