### ISSUE TITLE
If change happens on both ends, VCS wins

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2030]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1243101](https://bugzilla.mozilla.org/show_bug.cgi?id=1243101)
Bug Reporter: @mathjazz
CC:   @flodolo, @MikkCZ

If a translation is changed in both, VCS and Pontoon between two sync cycles, VCS translation should be impored into Pontoon and translation submitted via Pontoon should be degraded to a suggestion.

**Comment by eemeli** [comment]
Currently, Pontoon wins in this case.

@mathjazz Do you still think that the reverse should hold?

**Comment by mathjazz** [comment]
As agreed with @flodolo, let's wontfix.
