### ISSUE TITLE
Make translate view responsive

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2032]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1243132](https://bugzilla.mozilla.org/show_bug.cgi?id=1243132)
Bug Reporter: @mathjazz
CC:   anweshknayak@gmail.com, ranjithraj@riseup.net
Depends on:   [Bug 1586820](https://bugzilla.mozilla.org/show_bug.cgi?id=1586820)

Show entity list by default and open editor when entity selected. No in-page localization.

**Comment by mathjazz** [comment]
Work split into multiple issues:
https://github.com/mozilla/pontoon/issues/3026
https://github.com/mozilla/pontoon/issues/3027
https://github.com/mozilla/pontoon/issues/3028
https://github.com/mozilla/pontoon/issues/3029
