### ISSUE TITLE
Add ability to write custom plugins for the custom formats of resource files.

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2041]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1310735](https://bugzilla.mozilla.org/show_bug.cgi?id=1310735)
Bug Reporter: @jotes
CC:   @mathjazz

Hi,

I want to prepare a demo site for The Piwik project (http://piwik.org). Unfortunately, piwik uses custom format (.json) for keeping source strings and translation.

And because of that I think that we should add a possiblity to write plugins for the new formats of files

I think we can achieve this via the setuptools mechanism for plugins: http://docs.pylonsproject.org/projects/pylons-webframework/en/latest/advanced_pylons/entry_points_and_plugins.html

**Comment by mathjazz** [comment]
We're moving parsers and serializers to https://github.com/mozilla/moz-l10n/.
