### ISSUE TITLE
Link commits to bug in Bugzilla

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2046]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1321322](https://bugzilla.mozilla.org/show_bug.cgi?id=1321322)
Bug Reporter: @MikkCZ
CC:   @mathjazz, mvasicek@mozilla.cz
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1403287

This will have very low priority I guess, but each time there is a bug report in Bugzilla, I would like to be able to link the commit fixing it. In Bugzilla it is easy - I can paste the hg.mozilla.org URL after Pontoon syncs. But there is currently no way to link the other way from the changeset to Bugzilla to give the context to anyone looking in the VCS history only, except using the VCS directly and not Pontoon.

It would be nice to be able to add bug number when making changes in Pontoon, or more universal a text comment to include it in the commit message.

**Comment by mathjazz** [comment]
This seems like to little bang for the buck, so we're dropping it.
