### ISSUE TITLE
Add an option to link to multiple strings

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2049]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1324933](https://bugzilla.mozilla.org/show_bug.cgi?id=1324933)
Bug Reporter: @tomer
CC:   @gaby2300, @ItielMaN, @mathjazz
Blocker for:  [Bug 1390931](https://bugzilla.mozilla.org/show_bug.cgi?id=1390931)

In dxr.mozilla.org I can select multiple lines in a file and than have a link that will show these lines highlighted. I'd suggest having a similar feature in pontoon, so we could send a team member a link that contains multiple strings, instead of one of the following workarounds:

* Sending one string per link
* Sending link to a search results or a resource, and asking them to look on the second string, the third from the bottom, etc. 

I'd like to have a link similar to this one: 
https://pontoon.mozilla.org/he/firefox-aurora/all-resources/?string=75295,75296 
… Which will show me both strings in the list.

As for the UI for creating such lists, I guess having control-click to toggle multiple selections will be enough; this is an advanced feature after all. ☺

**Comment by eemeli** [comment]
This should make it easier to resolve #2276 as well.
