### ISSUE TITLE
Show indication for good results from Translation Memory

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2050]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1325525](https://bugzilla.mozilla.org/show_bug.cgi?id=1325525)
Bug Reporter: @tomer
CC:   @ItielMaN, @mathjazz

Sometimes you start translating something that is very similar to previous translations. For example, I'm currently translating Firefox for iOS, which has large amount of strings that are identical to strings from the Android equivalent or the desktop browser. 

Currently we have few options:
* Translate everything manually.
* Use Translation Memory for hints, manually copy strings that are identical to previous translations. 
* Use Translation Memory to blind translate automatically, maybe never actually make sure that everything is correct. 

The second option is a good balance between automatic translation and manual, and  allow us to make sure we won't mess with bad translation as the interaction require human review. 

I'd suggest adding a visible indication when there is a good chance that the same string have been already translated in the past. I mean that there is an item in the Machinery tab that received from a trusted source (we trust only ourselves, so only Mozilla stings are trustfully) with a good score (no less than 100 percents!), a visible icon should appear in the panel above the tabs, with an option to copy the translation in one click. 

I'd also suggest highlighting good results, because most of the times we WANT the translator to at least read the suggestions, as the translated terms are already there. 

Having better TM usage will make sure that we do less mistakes and keep the translations identical between platforms and different resources, and at the same time speed up translations.

**Comment by eemeli** [comment]
Starting to consider this one. Seems to me that we ought to get the desired outcome if, when a new string is added, we were to immediately generate a new suggestion from a 100% TM match. That would then also show up in the edit field for translators.

@flodolo, @mathjazz Do you see any reason why that would be a bad idea?

**Comment by mathjazz** [comment]
When would such suggestion be created?

**Comment by eemeli** [comment]
Primarily I was thinking of doing it when new entities are created. May need a couple of other places as well, such as when a project is added or a new locale is enabled for a project.

**Comment by mathjazz** [comment]
OK, so this would effectively be a special use case of pre-translation (enabled across all projects and locales implicitly, and only engaging TM). It would also affect Unreviewed counts.

One alternative would be to visually "fake" such suggestions in the History panel (and the editor?).

**Comment by flodolo** [comment]
This report is from a time when the MACHINERY tab wasn't displayed by default, so it would be easy to miss a 100% match. 

I honestly don't know if this feature request makes still sense with the current 3 columns layout. Is there value in highlighting a 100% match to differentiate it from others? Maybe, it depends on how.

I think creating actual suggestion would be something that pretranslation should take care of. Side note: multiple 100% matches are possible, and not necessarily a consistency issue.

**Comment by eemeli** [comment]
> One alternative would be to visually "fake" such suggestions in the History panel (and the editor?).

If the TM suggestions are faked, then they wouldn't show up with the `status=unreviewed` filter.

> I honestly don't know if this feature request makes still sense with the current 3 columns layout. Is there value in highlighting a 100% match to differentiate it from others? Maybe, it depends on how.

Probably not, tbh?

> I think creating actual suggestion would be something that pretranslation should take care of. Side note: multiple 100% matches are possible, and not necessarily a consistency issue.

You're right, this does look an awful lot like pretranslation.

Multiple matches isn't actually a problem, as we could add multiple suggestions for each of them. Same actually goes for pretranslation hits.

Should we mark this as `wontfix`, noting that the default-display and pretranslation does and will solve the core issue?

**Comment by mathjazz** [comment]
> I honestly don't know if this feature request makes still sense with the current 3 columns layout. Is there value in highlighting a 100% match to differentiate it from others? Maybe, it depends on how.

> Should we mark this as `wontfix`, noting that the default-display and pretranslation does and will solve the core issue?

"Pre-fill editor with 100% Translation Memory matches when available" was the 2nd most voted feature from the H1 2022 community survey.

**Comment by eemeli** [comment]
Okay, so it looks like my suggestion could be rephrased as this:

1. Replace the current on/off pretranslation setting with something that allows more tuning.
2. As one of the options, include a minimum match for TM.
3. Change the default settings to apply pretranslation for 100% TM matches.
