### ISSUE TITLE
Implement auth0 provider

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2051]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1326336](https://bugzilla.mozilla.org/show_bug.cgi?id=1326336)
Bug Reporter: @jotes
CC:   david.ascher@gmail.com, @mathjazz
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1558484

Pontoon currently allows to log-in via Firefox Accounts, however we may need to support Auth0 as it's suggested by Mozilla's Cloud Security team.

This bug will probably require an implementation of Auth0 provider in django-allauth.
Also, We should think about ui-interface that would allow to merge accounts between auth0 and Firefox Accounts (in the similar fashion as it was done during the migration from Persona).

**Comment by mathjazz** [comment]
Closing, because we have other ways of authentication for 3rd parties now.
