### ISSUE TITLE
Remove bilingual files removed from repository

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2057]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1345431](https://bugzilla.mozilla.org/show_bug.cgi?id=1345431)
Bug Reporter: @mathjazz
CC:   @TheoChevalier

Projects using bilingual file formats (xliff, po, lang...) can have different files exposed for each locale. If the file is added to the locale folder in repository, we detect it and enable it Pontoon. If it's removed, we also detect it, but don't remove it from Pontoon.

This doesn't happen often, but it still does:
https://github.com/mozilla-l10n/engagement-l10n/commit/7bac95f3d0ced07a109d5bb8f9497fe8fa9568a4

Implementations notes:
Files are represented with an instance of the TranslatedResource model. If an instance exist for the given locale, we expose the file in Pontoon. When a file is removed from the repository, we need to remove the TranslatedResource instance and aggregate denormalized stats for the corresponding Project, Locale and ProjectLocale instance.

Unlike changed_source_files(), changed_locales_files() ignores removed_files:
https://github.com/mozilla/pontoon/blob/master/pontoon/sync/vcs/models.py#L129

**Comment by mathjazz** [comment]
Bumping priority, because the bug might hit us again soon after we stop using project configuration for "Foundation website - content".

**Comment by flodolo** [comment]
@mathjazz 
Is it expected to have a P1 issue open for so long?

**Comment by mathjazz** [comment]
No. :)

This should be taken care of as part of the "Improve Pontoon sync reliability" OKR.

Also, P1 was probably to high priority in first place.
