### ISSUE TITLE
Tracking changes in the translation text field

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2062]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1357834](https://bugzilla.mozilla.org/show_bug.cgi?id=1357834)
Bug Reporter: @guerojeff
CC:   @flodolo, @Pike, @Delphine, @mathjazz, @peiying2
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1203265

Rather than contact fellow localizers about changes they need to make to a translation, reviewers often make changes themselves and don't notify the translator. To support that inclination + the need to provide translators with feedback, changes should be tracked and compiled into a report delivered to translators on a regular basis (e.g., all changes made by reviewers per day as a report accessed through notifications or viewed in email). If changes are tracked, they can then be attributed to an alternate user through an alternate action that is enabled when Pontoon detects that a translation has been changed (e.g., 'Suggest/Submit' button changes to 'Submit edits' or something like that when Pontoon detects that a text field with translated content is activated and changed (maybe through edit distance metric?)).

**Comment by mathjazz** [comment]
This issue has been split into the following two:
* #2356
* #2357
