### ISSUE TITLE
On source repo change, import translations from corresponding l10n files

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2068]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1372151](https://bugzilla.mozilla.org/show_bug.cgi?id=1372151)
Bug Reporter: @flodolo
CC:   @guerojeff, @Pike, leandro.regueiro@gmail.com, @Delphine, @mathjazz, @MikkCZ, @TheoChevalier
Blocker for:  [Bug 1361017](https://bugzilla.mozilla.org/show_bug.cgi?id=1361017)

https://hg.mozilla.org/mozilla-central/diff/27cad9749cdd/mobile/android/base/locales/en-US/android_strings.dtd

This changeset resurrects two strings in android_strings.dtd

Since the changeset backed out landed after bug 1361017, those strings were never removed from the file, e.g. for cs
https://hg.mozilla.org/l10n-central/cs/file/dfe6771ce975/mobile/android/base/android_strings.dtd#l289

Nonetheless, Pontoon doesn't read them from the file and show them as missing.

**Comment by mathjazz** [comment]
We no longer use per-locale repositories and #3312 removes support for them (see #3303).

That means this bug can no longer occur.
