### ISSUE TITLE
CSP error on Pontoon pages

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2073]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1377831](https://bugzilla.mozilla.org/show_bug.cgi?id=1377831)
Bug Reporter: @MikkCZ
CC:   @alex-mayorga, @mathjazz
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1336076

In the browser console I see:

Content Security Policy: Nastavení stránky zablokovalo načítání zdroje na self („script-src https://pontoon.mozilla.org 'unsafe-eval' 'sha256-x3niK4UU+vG6EGT2NK2rwi2j/etQodJd840oRpEnqd4=' 'sha256-fDsgbzHC0sNuBdM4W91nXVccgFLwIDkl197QEca/Cl4=' https://ssl.google-analytics.com/ga.js“). Source: onfocusin attribute on DIV element. netmonitor.properties

**Comment by mathjazz** [comment]
I can no longer reproduce this issue.
