### ISSUE TITLE
Speed up team permissions page

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2075]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1379149](https://bugzilla.mozilla.org/show_bug.cgi?id=1379149)
Bug Reporter: @mathjazz
CC:   @MikkCZ, @jotes, @phlax
Depends on:   [Bug 1380349](https://bugzilla.mozilla.org/show_bug.cgi?id=1380349)
Blocker for:  [Bug 1397725](https://bugzilla.mozilla.org/show_bug.cgi?id=1397725)
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1432179

Team permissions page (pontoon.teams.views:ajax_permissions) is slow.

New Relic Data for the last 7 days
==================================
Apdex: 0.07
Count: 48
Avg: 3,210 ms
SD: 2,360 ms
Min: 47.2 ms
Max: 11,200 ms

Setting priority to P3, as this view is less used than filtering entities (bug 1377099) or contributors dashboards (bug 1357361).

**Comment by mathjazz** [comment]
Closing as dupe of #2289.
