### ISSUE TITLE
Translation view does not remember the frames width

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2081]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1385093](https://bugzilla.mozilla.org/show_bug.cgi?id=1385093)
Bug Reporter: @MikkCZ
CC:   anweshknayak@gmail.com, @mathjazz

STR:
1) Go to translate any project.
2) Point your mouse cursor on the frames edge, between the list of strings and translation input + helpers.
3) Change the width of the list of strings, e.g. shrink it to 1/4 of the screen.
4) Press F5 to reload the page.
5) The frames width is half of the screen again.

It would be nice if Pontoon remembers the frames width, stores somewhere in the browser, so it survives reloading the page or even closing and opening tab/browser again. IMO it does not have to be stored server side, as the desired width may vary for different devices.

**Comment by mathjazz** [comment]
This is blocked by #2183.

**Comment by mathjazz** [comment]
Let's track this in https://github.com/mozilla/pontoon/issues/2183.
