### ISSUE TITLE
Text area to enter notifications should have a preview function

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2088]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1396038](https://bugzilla.mozilla.org/show_bug.cgi?id=1396038)
Bug Reporter: @flodolo
CC:   @mathjazz

It would be great to have a preview of the notification you're sending, especially if it includes HTML.

I've just sent one forgetting to add paragraphs.

**Comment by mathjazz** [comment]
Messaging Center support that.
