### ISSUE TITLE
[notifications] Notify project Translators when suggestions are submitted

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2093]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1398861](https://bugzilla.mozilla.org/show_bug.cgi?id=1398861)
Bug Reporter: @mathjazz
CC:   @MikkCZ, mvasicek@mozilla.cz
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1625102

We should probably do that periodically and aggregate notifications.

**Comment by mathjazz** [comment]
Quick spec:

A daily job sends notifications about newly added unreviewed suggestions that are submitted, unapproved or unrejected in the last 24 hours. Recipients of notifications are users with permission to review them, as well as authors of any previous translations or comments of the same string. Users get 

Recipient gets only one notification, with all project-locale combinations aggregated. Example:

*Unreviewed suggestions have been submitted for the following projects:*
- *[Firefox for Android](https://pontoon.mozilla.org/sl/firefox-for-android/all-resources/?status=unreviewed)*
- *[Mozilla.org](https://pontoon.mozilla.org/sl/mozillaorg/all-resources/?status=unreviewed)*

@flodolo @Delphine @peiying2 r?

**Comment by flodolo** [comment]
Is it 24 hours too often, given users can't opt out of notifications? 
What happens is a suggestion is submitted but already approved within the interval? I assume we wouldn't send anything in that case?

**Comment by Delphine** [comment]
I think every 24h is going to be to much noise for localizers. Could once a week already be enough?

**Comment by mathjazz** [comment]
> What happens is a suggestion is submitted but already approved within the interval? I assume we wouldn't send anything in that case?

Your assumption is correct.

**Comment by keunes** [comment]
> Recipients of notifications are users with permission to review them

This would be project managers and language team coordinators? (Sorry, don't know the Pontoon terms by heart.)

**Comment by mathjazz** [comment]
It's team Managers and Translators:
https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/users.html#user-roles

**Comment by peiying2** [comment]
24-hour cycle seems to be frequent, but most people don't check Pontoon daily. We also assume people translate/review in Pontoon daily in all the projects. I personally don't object it it.
