### ISSUE TITLE
Perform search on filtered translations only

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2096]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1399839](https://bugzilla.mozilla.org/show_bug.cgi?id=1399839)
Bug Reporter: @TheoChevalier
CC:   felix.bau@gmx.de, @flodolo, @mathjazz, @jotes

Right now when performing a search, it provides matches from:

- The source string
- The approved translation
- Any pending or rejected suggestion
- Localization notes
- The string name (and probably full path)

I would like to be able to perform a search on the approved translations only, to reduce the number of false positives.

It would be particularly useful when performing searches related to punctuation mistakes, but there are other type of searches where it would help, like for words similar in English and the target language

**Comment by mathjazz** [comment]
- Pontoon no longer searches in comments.
- Searching in rejected translations is disabled by default.
- One can optionally search in translation only.
- Once #3284 lands, searching in string IDs will also be optional.

I think these changes resolve this bug.
