### ISSUE TITLE
Grow editing area to fit as many fields as possible

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2100]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1406576](https://bugzilla.mozilla.org/show_bug.cgi?id=1406576)
Bug Reporter: Khaled Hosny &lt;<dr.khaled.hosny@gmail.com>&gt;
CC:   @mathjazz, @zbraniecki

Arabic has 6 plural forms, but but only 4 are shown at a time and one has to scroll up and down to navigate between them which becomes annoying after editing a few of them. For example: 

https://pontoon.mozilla.org/ar/firefox-screenshots/all-resources/?status=missing&string=168582

**Comment by mathjazz** [comment]
Fixed in https://github.com/mozilla/pontoon/pull/2868.
