### ISSUE TITLE
Pontoon profile should have a GitHub and Bugzilla field

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2112]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1425801](https://bugzilla.mozilla.org/show_bug.cgi?id=1425801)
Bug Reporter: @flodolo
CC:   @mathjazz, @MikkCZ

Not sure if this should be a generic input field used to point to external services, but I know it would be extremely useful to have at least:
* The email address used for Bugzilla. A lot of new localizers don't have one, in some cases it doesn't match the email used on Pontoon.
* Their profile on GitHub.

**Comment by mathjazz** [comment]
This has been implemented as part of the Profile redesign.
