### ISSUE TITLE
Feature request to allow for private projects

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2127]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1457439](https://bugzilla.mozilla.org/show_bug.cgi?id=1457439)
Bug Reporter: exile@chamber.ee
CC:   @mathjazz

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Build ID: 20180326160923

Steps to reproduce:

N/A

Actual results:

Currently the anonymous user is able to see all the l10n strings for everything.

Expected results:

A project should have an extra option flag that allows the project to be set as "Private". In this case the project nor its content is listed/shown for anonymous (non-logged in) users and even logged in users who lack any team permissions (Contributor, Translator, Manager) in scope of that project. Pontoon superusers would still be able to see everything.

**Comment by mathjazz** [comment]
This feature has already landed:
https://github.com/mozilla/pontoon/pull/1619
