### ISSUE TITLE
GitHub services are being deprecated

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2140]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1486391](https://bugzilla.mozilla.org/show_bug.cgi?id=1486391)
Bug Reporter: @adngdb
CC:   dylan@hardison.net
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1486771
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1351785

GitHub announced they were deprecating its Services feature. According to their documentation: 

> Deprecation timeline
> *   October 1, 2018: GitHub discontinues allowing users to install services. 
>     GitHub Services will be removed from the GitHub.com UI.
> *   January 31, 2019: GitHub stops delivering installed services' events on GitHub.com.

On Pontoon, we currently use: 

- Bugzilla
- IRC
- ReadTheDocs
- Travis CI

We need to move those services to webhooks or GitHub Apps.

GitHub announcement: https://developer.github.com/changes/2018-04-25-github-services-deprecation/
GitHub documentation: https://developer.github.com/v3/guides/replacing-github-services/

**Comment by mathjazz** [comment]
This issue became obsolete as part of the Bugzilla to GitHub migration.
