### ISSUE TITLE
Create a light theme and enable switching to it

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2141]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1486503](https://bugzilla.mozilla.org/show_bug.cgi?id=1486503)
Bug Reporter: @adngdb
CC:   @mathjazz

As part of the effort to make Pontoon themable and customizable, we want to start by creating a light theme (as opposed to the current dark one) and allowing users to switch to that theme.

This should be the first step towards enabling greater theming and customizations, maybe by letting users creating their own themes?

**Comment by mathjazz** [comment]
Since this is also an a11y issue, we should also check contrast with something like https://webaim.org/resources/contrastchecker/ and consult Mozilla a11y team.

**Comment by mathjazz** [comment]
Tracked in #2933, #2934, #2935, #2936.
