### ISSUE TITLE
Find in page doesn't find all results in scrollable elements like div with overflow-y: auto

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2145]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1497511](https://bugzilla.mozilla.org/show_bug.cgi?id=1497511)
Bug Reporter: Djfe &lt;<felix.bau@gmx.de>&gt;
CC:   @adngdb, djibe89@hotmail.com, standard8@mozilla.com, VYV03354@nifty.ne.jp
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=407817

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

Steps to reproduce:

Used Pontoon and searched for several strings:
current
Eircode
shortcuts
department
clear all

URL:
https://pontoon.mozilla.org/de/firefox/all-resources/?status=missing&string=190786

This probably won't be reproducable because those strings won't stay untranslated for long (I have to keep working after all), but you should be able to reproduce my results in the translated strings as well.

here you can actually see, what I did:
https://www.youtube.com/watch?v=P5Kfs04zGsM

Actual results:

current:
11 results
1, 7-11 are reachable, 2-6 aren't unless I manually scroll down

Eircode:
Not found even though it's there

shortcuts and department: work fine for some reason

clear all:
same issue as Eircode

**Comment by mathjazz** [comment]
I can no longer reproduce this issue.
