### ISSUE TITLE
Users should have a way to contact existing locale managers

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2157]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1516164](https://bugzilla.mozilla.org/show_bug.cgi?id=1516164)
Bug Reporter: @flodolo
CC:   @mathjazz

I don't think there's an easy way for contributors to get in touch with existing managers or translators, even if it's something we suggest to do when they ask for new projects.

There's an INFO tab, but few of them customize it. Maybe we should have a TEAM tab, that lists all managers and translators for a team.

We could also have a "contacts" tab, with a form to get in touch with the team, accessible only to registered users.

**Comment by mathjazz** [comment]
At least as the first step, I'd group contributors by role in the Team Contributor tab.
