### ISSUE TITLE
Set all translation authors and commit authors

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2158]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1522112](https://bugzilla.mozilla.org/show_bug.cgi?id=1522112)
Bug Reporter: @mathjazz
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1521288

Ideally, Pontoon should split commits containing translations from multiple authors into multiple commits, one for each author.

Such change would require a pretty serious refactoring of our sync code, so we should start with a simpler, short-term solution.

Instead of setting one user (the one with most contributions) as the commit author, we should set all contributors as authors.

**Comment by eemeli** [comment]
During the discussions around #3312, we determined not to do this.
