### ISSUE TITLE
Hebrew hyphen takes no space in textarea

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2159]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1526686](https://bugzilla.mozilla.org/show_bug.cgi?id=1526686)
Bug Reporter: roigby@gmail.com
CC:   @flodolo, @ItielMaN, @mathjazz, @yarons, @tomer

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

Steps to reproduce:

insert the hyphen character to the pontoon textarea (unicode #1470 - https://en.wiktionary.org/wiki/־).

Actual results:

the character took no horizontal space at the textarea, resulting in no spacing between words.
this is due to the "Lucida Sans Unicode" font familiy attributed to the textarea's style.

Expected results:

should have acted as a dash/hyphen (separate between adjacent words).

**Comment by flodolo** [comment]
@ItielMaN

Are you still seeing this with the new editor?

**Comment by ItielMaN** [comment]
It doesn't, but it does in the testcase mentioned above.
At this point I'm not sure if this is a Windows/font issue or a Firefox issue, as I can also reproduce this in Chrome.

In any case this issue can be closed I think.
