### ISSUE TITLE
Add support for banning users

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2164]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1543695](https://bugzilla.mozilla.org/show_bug.cgi?id=1543695)
Bug Reporter: @flodolo
CC:   @Pike, @Delphine, @mathjazz, @peiying2

In case a user is banned from contributing to Mozilla (CPG violation, or just spam on Pontoon), there's currently no easy way to ban them. 

We can demote them, removing all permissions they have, but that doesn't prevent them from being toxic in suggestions.

I think we should be able to ban a user. Effects should at least be:
* User can't provide suggestions. Everything is read-only for them.
* User can't be promoted to active roles (translator, manager).
* Profile shows that the user has been banned and is locked (they can't edit their name, for example, to something offensive).

I'm not completely sure we should go as far as to remove them from attribution by default.

**Comment by mathjazz** [comment]
This has been fixed a while ago:
https://mozilla-l10n.github.io/documentation/tools/pontoon/deactivating_users.html
