### ISSUE TITLE
Detecting localizable files is not strict enough

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2170]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1558466](https://bugzilla.mozilla.org/show_bug.cgi?id=1558466)
Bug Reporter: @mathjazz

Pontoon only uses [file extensions](https://github.com/mozilla/pontoon/blob/5c57d80/pontoon/sync/utils.py#L19) to detect localizable files.

That check is often insufficient. We've had problems especially with wrong .json and .xml files being erroneously detected as localizable files, since they are not localization-specific formats. See bug 1558465 for example.

We should make the check for detecting localizable files stricter.

**Comment by mathjazz** [comment]
Pontoon support Project configuration files, which cover more complex file and folder structures:
https://mozilla-pontoon.readthedocs.io/en/latest/user/localizing-your-projects.html#folder-structure
