### ISSUE TITLE
Ability to request projects per files in Pontoon

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2172]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1564222](https://bugzilla.mozilla.org/show_bug.cgi?id=1564222)
Bug Reporter: @Delphine
CC:   @guerojeff

Right now, in the android-l10n project on Pontoon, users can't request a specific product to localize: it's either all of android-l10n files or nothing.
Since the  locale lists differ from one android-l10n project to another, it would be helpful if people could request specific projects directly for their locale (instead of me having to do that).
So for example:
* Request Fenix (which is Fenix file + a-c files)
* Request Fx Reality (Reality file + a-c files)
etc.
I don't know to which point this is feasible, so I'm open to similar suggestions, or any idea that can help improve this current situation :)

**Comment by mathjazz** [comment]
Android L10n project has been long gone, so this is no longer relevant.
