### ISSUE TITLE
Simplify plurals UI for locales with single plural form

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2179]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1581813](https://bugzilla.mozilla.org/show_bug.cgi?id=1581813)
Bug Reporter: @mathjazz

We should change the way getEmptyMessage() handles plural forms for locales with only one plural form (e.g. Chinese): we should drop the SelectExpression completely and replace it with a simple TextElement.

That will in turn result in a single <textarea> element to be rendered for a "Plural Expression".

Background:
https://github.com/mozilla/pontoon/pull/1379#issuecomment-531228523

**Comment by mathjazz** [comment]
This has been fixed.
