### ISSUE TITLE
Switch to Google Translate API v3

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2184]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1588465](https://bugzilla.mozilla.org/show_bug.cgi?id=1588465)
Bug Reporter: @mathjazz
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1552796

We should look into switching from Google Translate API v2 to v3Beta:
https://cloud.google.com/translate/docs/intro-to-v3

**Comment by mathjazz** [comment]
We have added support for AutoML Translation in #2648, which makes this request obsolete.
