### ISSUE TITLE
Problem while saving FTL string with only "other" plural variant in string

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2186]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1589113](https://bugzilla.mozilla.org/show_bug.cgi?id=1589113)
Bug Reporter: Håvar I. Henriksen [:havarh] &lt;<havar@firefox.no>&gt;
CC:   @flodolo, @Pike

Created attachment 9101569
User interface shown when FTL is activated.

I just tried to translate string number **204799** for Firefox, but I got an error **"The following checks has failed. Expected value"** when I tried to save the translation since the string only had an **"other"** in the plural variant of the string. That is, the **"one"** plural variant is empty. See screen shot.
What I had to do is turn off FTL for that string, and then copy over the English FTL code and edit that directly.
The comment on this string reads: **"This number will always be greater than 1"**, and that's why the **"one"** plural form is missing.

https://pontoon.mozilla.org/translate/nb-NO/firefox/all-resources/?string=204799

**Comment by mathjazz** [comment]
Not sure there are action items here for Pontoon. Please reopen if you think there are.
