### ISSUE TITLE
Empty attribute not displayed in the UI

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2188]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1591416](https://bugzilla.mozilla.org/show_bug.cgi?id=1591416)
Bug Reporter: @flodolo
CC:   @adngdb, @Pike, @mathjazz

https://pontoon.mozilla.org/translate/hy-AM/firefox/browser/browser/newtab/asrouter.ftl/?search=cfr-doorhanger-milestone-ok-button&string=204800

Committed to the repository: https://hg.mozilla.org/l10n-central/hy-AM/rev/e9eca9148f4ffdfc91703dacc3aa59bc2d333814#l4.84

And resulting in Junk

```
cfr-doorhanger-milestone-ok-button = Պահպանել բոլորը
    .accesskey = 
```

The `accesskey` attribute is not visible in the UI, unless you switch to the advanced FTL, where you'll see the empty accesskey. I think that's the main issue here, an empty attribute should show up.

**Comment by mathjazz** [comment]
This should have been fixed as part of another PR. Please reopen if the problem resurfaces.
