### ISSUE TITLE
Can switch from Rich editor to Simple via Source

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2190]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1592254](https://bugzilla.mozilla.org/show_bug.cgi?id=1592254)
Bug Reporter: @adngdb
CC:   @Pike, @mathjazz

It is possible to start with a string in the rich editor, edit it in the source editor, and get back to the simple editor when switching source mode off. I am not sure if that's a bug or a feature though.

## Steps to reproduce

1. Go to an FTL string with a value and a single attribute (e.g. https://pontoon.mozilla.org/translate/fr/firefox/devtools/client/application.ftl/?string=179386 ).
2. Clear the content of the value field.
3. Switch to Source mode (click the FTL button).
4. Switch back to Rich mode (click the FTL button again).

## Expected result

You get back to the rich editor with an empty Value field.

## Actual result

The Simple editor shows up, with only the content of the attribute.

**Comment by mathjazz** [comment]
This issue has been fixed.
