### ISSUE TITLE
[translate] Show that "save" button can also approve translations

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2193]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1599075](https://bugzilla.mozilla.org/show_bug.cgi?id=1599075)
Bug Reporter: @adngdb
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1606302

When the translation loaded in the editor is the same as one that already exists, and the user with sufficient privileges presses "Save" or hits Enter, the translation gets approved. That is a shortcut useful for people who do a lot of reviews, as they can easily just hit Enter to approve and move to the next translation.

However, the UI never shows that this would be the behavior. We should change the button label to "Approve" when the content of the editor is the same as one of the existing translations. 

We should also change the backend to remove the `update_translation` view and replace it with calls to a new `create_translation` view or to the existing `approve_translation`.

**Comment by mathjazz** [comment]
This has been fixed.
