### ISSUE TITLE
Migrate historic data into ActionLog table

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2196]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1599387](https://bugzilla.mozilla.org/show_bug.cgi?id=1599387)
Bug Reporter: @adngdb
CC:   @mathjazz

We intend to use the ActionLog table to fuel a bunch of features, such as latest activity, various timelines (user, project, team… ) and so on. In order not to lose data, we want to migrate as much data as we can from our existing tables into the ActionLog table.

Most of the data we want to migrate is in the Translation table, and that's the review actions data (approved date, approved user, and so on).

Matjaz, is there anything else we want to migrate?

**Comment by RafaelJohn9** [comment]
@mathjazz , would love to be assigned this issue.
