### ISSUE TITLE
Remove Python 2-specific code parts

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2199]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1600344](https://bugzilla.mozilla.org/show_bug.cgi?id=1600344)
Bug Reporter: @adngdb
CC:   hexagonrecursion@gmail.com
Depends on:   [Bug 1585253](https://bugzilla.mozilla.org/show_bug.cgi?id=1585253)

In our migration to Python 3, we are adding code paths specific to Python 2. Once we are fully ported to Python 3 and have dropped support of Python 2, we should remove all py2-specific code.

Let's use this bug to mark such parts in our code base.

**Comment by flodolo** [comment]
Assuming this is done at this point.
