### ISSUE TITLE
Mixed RTL and LTR content is hard to read in marked placeables

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2200]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1602426](https://bugzilla.mozilla.org/show_bug.cgi?id=1602426)
Bug Reporter: @Pike
CC:   @amire80, @flodolo, @mathjazz, mahtab.ceh@gmail.com, myaseen.khan@hotmail.com, safa1996alfulaij@gmail.com, shahbazalam17feb@gmail.com
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1500333

+++ This bug was initially created as a clone of Bug #1500333 +++

Looking at our marked placeables with mixed RTL and LTR code, the bidi algorithm on not kicking in on `<>` as braces still hurts us.

I think it'd be a good idea to do bidi-isolation or even strong directional hints when we mark up placeables.

**Comment by mathjazz** [comment]
Seems like https://github.com/mozilla/pontoon/issues/2267 was a dupe of this.
