### ISSUE TITLE
Allow users to customize their profile URL

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2203]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1604554](https://bugzilla.mozilla.org/show_bug.cgi?id=1604554)
Bug Reporter: Mehul Patel &lt;<iamrowdymehul@gmail.com>&gt;
CC:   @flodolo, @mathjazz

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0

Steps to reproduce:

Login to Pontoon >> Navigate to your Profile picture and look at the URL in the browser. 

Actual results:

It shows like this: E.g. https://pontoon.mozilla.org/contributors/wNLHdL7tCYar1cu5Q3OvsfS6qGY/

Expected results:

It should show like: E.g. https://pontoon.mozilla.org/contributors/mehulpatel

Another example: https://mozillians.org/en-US/u/rowdymehul/

It would be great if we can do something like this. Let me if I can help in anyways.

**Comment by mathjazz** [comment]
A dupe of #2483.
