### ISSUE TITLE
Add support for continuous l10n timelines with milestones

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2210]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1614618](https://bugzilla.mozilla.org/show_bug.cgi?id=1614618)
Bug Reporter: @Pike
CC:   @mathjazz

Right now, Pontoon only supports deadlines. But most of our projects don't have a deadline. Instead, they have multiple dates in the future that are good for localizers to know about.

I'll spec something out for this feature.

**Comment by mathjazz** [comment]
As suggested in https://github.com/mozilla/pontoon/pull/1565#issuecomment-1040420250 and the followup team meeting, let's instead improve the existing "Deadlines" functionality:

https://github.com/mozilla/pontoon/issues/2433
https://github.com/mozilla/pontoon/issues/2434
