### ISSUE TITLE
Sync stops running after Scheduler Cycling

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2215]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1617539](https://bugzilla.mozilla.org/show_bug.cgi?id=1617539)
Bug Reporter: @mathjazz

The following sync task stopped running:
https://pontoon.mozilla.org/sync/log/100997/

There aren't any errors in the logs, the last message from the worker running the task was:

```
Feb 24 02:05:25 mozilla-pontoon app/worker.1 [2020-02-24 02:05:24,789: INFO/ForkPoolWorker-188] Fetching latest commit hashes for project thunderbird started.
```

The following sync task was interrupted by Cycling of the Scheduler:

```
Feb 24 02:13:25 mozilla-pontoon heroku/scheduler.1483 Cycling
```

At the subsequent tasks failed to run until the worker was manually restarted.

We don't know if the tasks were piling up in the queue like they did in bug 1477570, but we know that (at least some of) the documented fixes for that bug didn't resolve the problem (e.g. flower doesn't show any data anymore).

As part of this bug, we should:
1. Investigate, what prevented sync jobs from running.
2. Find the solution for it.
3. Update the [maintenance docs](https://mozilla-pontoon.readthedocs.io/en/latest/admin/maintenance.html#releasing-the-queue).
4. Extend the list of recipients of the "Sync complete" alert.

**Comment by mathjazz** [comment]
Closing as we haven't seen another instance of this problem. 🤞
