### ISSUE TITLE
Fix display of Translations with Errors

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2217]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1618920](https://bugzilla.mozilla.org/show_bug.cgi?id=1618920)
Bug Reporter: @mathjazz
CC:   @adngdb
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1686402

Bug 1584180 forces checks on pretranslations, which greatly increases the probability of Translations with Errors getting into Pontoon (Pontoon blocks saving Translations with Errors when submitted via Translate Workbench).

Fluent Translations with Errors are sometimes not displayed at all (the editor is empty or contains the previous translations) or are displayed without the corresponding error message. We should fix that.

**Comment by mathjazz** [comment]
This should be fixed.
