### ISSUE TITLE
Add support for .strings file format

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2226]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1635284](https://bugzilla.mozilla.org/show_bug.cgi?id=1635284)
Bug Reporter: Woosuk Park &lt;<bjh13579@gmail.com>&gt;
CC:   @guerojeff, @mathjazz

Created attachment 9145636
lproj.zip

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0

Steps to reproduce:

I'm Using for mac, and translated for application is hobby. so if available, xcode strings(.strings) parsing for pontoon.

Actual results:

i upload english / Dutch lproj string. (from OnyX)

1. /* Class = "NSMenu"; title = "OnyX"; ObjectID = "57"; */
"57.title" = "OnyX";

2. "B_CANCEL" = "Annuleer";
"B_CONTINUE" = "Verder";

Expected results:

Nothing will happen, if available, translating in pontoon in Xcode strings.

**Comment by mathjazz** [comment]
Closing as per comment in https://github.com/mozilla/moz-l10n/pull/4#issuecomment-2082570376.
