### ISSUE TITLE
Rejected Fluent strings resurrected as imported and approved

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2228]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1638754](https://bugzilla.mozilla.org/show_bug.cgi?id=1638754)
Bug Reporter: @flodolo
CC:   @jordis

This is the string
https://pontoon.mozilla.org/hye/firefox/toolkit/toolkit/about/aboutAddons.ftl/?search=addon-detail-private-browsing-help&string=198326

On May 17 I've unapproved the translation and added comments, since the string was missing part of the mark-up. At least, I believe I did. It would be great to confirm that (via Action Log?), because that change never made it to the hg repository.

This morning I realized that the error was still  there, and now the string shows up as "Imported". Which is not possible, since nobody is making changes directly to Mercurial.

The string was originally committed to hg [here](https://hg.mozilla.org/l10n-central/hye/rev/4aff7d7f8dcb1d3b99424c4722bae8bccdf019d5#l1.72).

On top of that: 
* I believe I commented on the translation below (from Real School, at 09:51 UTC). 
* When switching to advanced view, this string and the one imported look identical. I guess there's some difference in how they're stored in the DB, but it's not showing up in the UI.

**Comment by mathjazz** [comment]
Seems related to #2216, but hard to tell at this point. Please reopen if the problem resurfaces.
