### ISSUE TITLE
Revisit sync process for XLIFF files

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2239]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1676336](https://bugzilla.mozilla.org/show_bug.cgi?id=1676336)
Bug Reporter: @flodolo
CC:   @guerojeff, @mathjazz, sstreich@mozilla.com

So far we've been using XLIFF only for iOS projects. For both projects (Firefox, Focus) we built an infrastructure that updates all locales when adding new strings to the reference file (en-US).

Currently, if you add new strings only to the reference file:
- Strings show up as missing for all locales
- The new translations are not submitted back to the repository, since the XLIFF is missing them
- "Download Translations" gives you a file that is missing translations, like the one in the repository.

The downside of this approach, besides being very confusing, is that we need to replicate the infrastructure for every repository. For example, this is the work happening for the new VPN client
https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/39

Unlike GetText, XLIFF doesn't come with native commands to propagate new strings to all locales. 

I think it would make more sense to be able to add new strings only to the reference locale, and have Pontoon add them to the resulting XLIFF file when serializing it.

**Comment by flodolo** [comment]
This is a problem also when a brand new file is added to an existing project (VPN uses multiple XLIFF files).
