### ISSUE TITLE
Machinery text replaces text in source editor instead of just adding it

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2244]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1682137](https://bugzilla.mozilla.org/show_bug.cgi?id=1682137)
Bug Reporter: @abowler2
CC:   @mathjazz

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0

Steps to reproduce:

Selected an entry in order to 'Copy into translation' from the machinery tab

Actual results:

When in the standard FTL view (table view) the editor text is replaced instead of just added to.

Expected results:

The text from the machinery tab should have just been added to the editor rather than replacing the editor contents.

**Comment by mathjazz** [comment]
In the meanwhile we have changed the behavior of copying strings from Machinery. Text is now replaced in both, the rich editor field or the source editor, but we always make sure the resulting Fluent message is valid. For example, when a value is copied to the source editor, that results in the following content: `source-string-id = Copied value`.
