### ISSUE TITLE
Back button doesn't update translation text

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2246]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1682558](https://bugzilla.mozilla.org/show_bug.cgi?id=1682558)
Bug Reporter: @julen

Steps to reproduce:
1. Open any FTL resource with multiple strings
2. Navigate to a string
3. Press 'Back' button

Observed:
- Translation text contains previous text contents

Expected:
- Translation text is updated to match contents for string ID

**Comment by mathjazz** [comment]
This is no longer happening.
