### ISSUE TITLE
Drop frontend stack used by the tag management widget

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2248]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1685818](https://bugzilla.mozilla.org/show_bug.cgi?id=1685818)
Bug Reporter: @mathjazz
Blocker for:  [Bug 1463368](https://bugzilla.mozilla.org/show_bug.cgi?id=1463368), [Bug 1608225](https://bugzilla.mozilla.org/show_bug.cgi?id=1608225)

The tag management widget in the admin panel uses a specific frontend stack - React, but separate from the one used by the frontend module.

We should drop it, possibly as part of fixing bug 1608225.

**Comment by eemeli** [comment]
Closing, as this was resolved in #2432.
