### ISSUE TITLE
Trigger search by clicking on magnifying glass icon in string list and machinery

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2249]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1685821](https://bugzilla.mozilla.org/show_bug.cgi?id=1685821)
Bug Reporter: @mathjazz
CC:   michele.rodaro@mozillaitalia.org

Since bug 1659491 has been fixed, we've heard reports from users they were expecting search to trigger after clicking on the magnifying glass icon. Additionally, Google Search also shares this behavior on the search results page.

Let's make the icon a button that triggers search when clicked.

**Comment by mathjazz** [comment]
#3221 will introduce a search menu that will open on click on the magnifying glass icon, which clashes with this request.
