### ISSUE TITLE
Migrating to GitHub issues

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2256]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1688846](https://bugzilla.mozilla.org/show_bug.cgi?id=1688846)
Bug Reporter: @mathjazz
CC:   @abowler2, adrian@gaudebert.fr, @Pike, @flodolo, @julen, keunes@mailbox.org, @Mitch4sho, @MikkCZ, @jotes
Depends on:   [Bug 1728575](https://bugzilla.mozilla.org/show_bug.cgi?id=1728575)

This is a conversation starter to evaluate the feasibility of using GitHub Issues instead of Bugzilla to track bugs for the Pontoon project.

Why GitHub?
* Already used as a critical tool, users don't need another account, barrier to entry is lower.
* It's easier to use. Input form, issues list and search have simpler UX.
* GitHub Issues are easier to reference from within GitHub (PRs, comments, commits...).
* We'll be able to close issues on commit automatically again (see 1486391).
* We'll be able to move roadmap from unmaintained Mozilla Wiki to GitHub.

Why Bugzilla?
* We don't need to do anything.
* We own it.
* Easier to make dependencies with other Mozilla projects (but we barely use that).
* Has established support for (private) security bugs.

**Comment by mathjazz** [comment]
Issue have been migrated to GitHub!

Adding a map of bug to issue IDs: [map.txt](https://github.com/mozilla/pontoon/files/7156822/map.txt).
