### ISSUE TITLE
Add ability to Re-apply existing filter

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2257]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1689716](https://bugzilla.mozilla.org/show_bug.cgi?id=1689716)
Bug Reporter: @mathjazz

Imagine you have 100 Unreviewed strings. You open them in the translate view and review 70 of them. Then you want to refresh the list to be able to move between the remaining 30 more quickly.

Selecting Unreviewed filter again doesn't do anything. You need to select a different filter first, and then Unreviewed again. That's an unnecessary step which shouldn't be, well... necessary. :)

This is also a regression introduce by Translate.Next.

**Comment by Mitch4sho** [comment]
May I be adding to this issue @mathjazz

**Comment by Mitch4sho** [comment]
If I wanted to ask more questions about this task, should I ask here or on element? @mathjazz

**Comment by mathjazz** [comment]
Either works. :)

The basic ideas is this: if you are in a translate view with [Unreviewed strings](https://mozilla-pontoon-staging.herokuapp.com/ab/common-voice/all-resources/?status=unreviewed&string=179345) filter applied, selecting Unreviewed filter again doesn't do anything. It should instead refresh the list.

The same is valid for any other filter, I'm just using Unreviewed as an example.
