### ISSUE TITLE
Brush up silme as used in Pontoon

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2265]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1692430](https://bugzilla.mozilla.org/show_bug.cgi?id=1692430)
Bug Reporter: @Pike
CC:   @julen, @mathjazz
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1696486

Matjaz' fork of silme on https://github.com/mathjazz/silme has at least a deprecation warning issue.

But it's also not possible to run the tests on py3, so there's a bit of cleanup work to do.

Matjaz, what do you think, should we remove code not used by Pontoon to reduce the amount of code we need to maintain there? Thinking about unused formats in https://github.com/mathjazz/silme/tree/master/lib/silme/format, and IOs in https://github.com/mathjazz/silme/tree/master/lib/silme/io, for example.

**Comment by mathjazz** [comment]
Seems to be fixed.
