### ISSUE TITLE
Only list pinned comments under all comments where posted

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2266]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1692619](https://bugzilla.mozilla.org/show_bug.cgi?id=1692619)
Bug Reporter: @mathjazz
CC:   @flodolo

Created attachment 9202996
Screenshot

We list pinned comments in the Pinned comments and All comments sections. That works fine in the translate view of the locale the pinned comment has been posted in, but not in translate views of other locales.

See screenshot for details.

**Comment by mathjazz** [comment]
@flodolo Do I understand correctly that all you want to do here is to remove the pinned comments from the all comments section? I think that makes sense if pinned comments are rewritten.

In this case we can keep the section titles and the design of the pinned comments unchanged.

**Comment by flodolo** [comment]
> @flodolo Do I understand correctly that all you want to do here is to remove the pinned comments from the all comments section?

Correct. In the screenshots above, they should be displayed only at the top, in "PINNED COMMENTS"
