### ISSUE TITLE
Set direction on placeables

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2267]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1692620](https://bugzilla.mozilla.org/show_bug.cgi?id=1692620)
Bug Reporter: @mathjazz

Created attachment 9202997
Screenshot

Everywhere we mark up placeables (i.e. everywhere we show strings in the translate view except in the textarea), we need to set the `dir` attribute to `ltr` in order to prevent bad display of placeables in RTL strings (as seen on the screenshot).

**Comment by nick-zanetti** [comment]
Could I have this assigned to me?

**Comment by mathjazz** [comment]
Done :)
