### ISSUE TITLE
Use the logical && operator when conditionally rendering a component

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2268]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1692699](https://bugzilla.mozilla.org/show_bug.cgi?id=1692699)
Bug Reporter: @abowler2
CC:   @mathjazz

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0

Steps to reproduce:

N/A

Actual results:

N/A

Expected results:

Currently when a component is rendered conditionally we are using the ternary operator: 

```
!condition ? null : <component>
```

Using the logical && operator would be a cleaner way to accomplish this:

```
condition && <component>
```

There are already some uses of the logical && operator that have been introduced in the code. In order to keep consistency we should consider replacing the ternary operator uses with the logical && operator.

**Comment by eemeli** [comment]
Closing as `wontfix`, as we appear to be keeping the current code style.
