### ISSUE TITLE
Use compare-locales instead of silme for serialization of dtd, inc, ini, properties

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2273]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1696486](https://bugzilla.mozilla.org/show_bug.cgi?id=1696486)
Bug Reporter: @Pike
CC:   @flodolo, @mathjazz
Blocker for:  [Bug 1611667](https://bugzilla.mozilla.org/show_bug.cgi?id=1611667)
See also:     https://bugzilla.mozilla.org/show_bug.cgi?id=1692430

While working on bug 1692430, I noticed that the parts that Pontoon uses from Silme are completely untested. What's worse, Pontoon relies on bugs at least in the ini parser.

There's nothing in Silme itself that helps Pontoon, so let's invest in converting sync to compare-locales for the now-Silme file formats.

This will require porting some hacks in the silme wrapper to the compare-locales wrapper, and porting the tests.

**Comment by mathjazz** [comment]
We'll be using parsers & serialisers from https://github.com/mozilla/moz-l10n/ and file an issue to implement that once the library is ready.
