### ISSUE TITLE
Autogrow rich editor fields to display the entire content

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2274]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1696722](https://bugzilla.mozilla.org/show_bug.cgi?id=1696722)
Bug Reporter: Baurzhan Muftakhidinov &lt;<baurthefirst@gmail.com>&gt;
CC:   @mathjazz

Currently when large string is copied from original to the edit field and when there are more than 1 field displayed (combined translation?, for example label and its accesskey in 2 fields, or more), I need to manually adjust height of edit fields so that I see more (or whole) string. Because in such combined messages translation fields are 1-rows.

Can the such edit fields autogrow when translation is copied from original via Copy button in Pontoon web interface?

**Comment by mathjazz** [comment]
Not just when the content is copied, the fields should always "autogrow", i.e. even when content is manually entered or already exists as reported in #2406.

**Comment by mathjazz** [comment]
See also #2100, which is (at least partially) in conflict with this issue.

**Comment by mathjazz** [comment]
Fixed in #2866.
