### ISSUE TITLE
Pontoon picks the wrong folder format for locales (underscore instead of hyphens)

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2277]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1698636](https://bugzilla.mozilla.org/show_bug.cgi?id=1698636)
Bug Reporter: @flodolo
CC:   @mathjazz

I created the repository with the source in `en-US` folder.
https://github.com/mozilla-l10n/mozilla-vpn-website-l10n/

Pontoon then synced `pt-BR` as `pt_BR`. One possible explanation is the presence of a file with underscores (`CODE_OF_CONDUCT.md`) in the repository. If that's the case, it's a bug, because we really care about folders, not files.

I then renamed `pt_BR` to use hyphens, synced translations for `en-CA` and it still used the wrong format (`en_CA`). Fixed this one too, synced a string for `en-GB`,  and again wrong format.

At this point, I don't know if it will keep using _ for the next locales.

**Comment by nick-zanetti** [comment]
Could I have this assigned to me?

**Comment by mathjazz** [comment]
Done!
