### ISSUE TITLE
Implement AB testing capability

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2282]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1701631](https://bugzilla.mozilla.org/show_bug.cgi?id=1701631)
Bug Reporter: @mathjazz
Blocker for:  [Bug 1695961](https://bugzilla.mozilla.org/show_bug.cgi?id=1695961)

We'd like to experiment with changes in the notification UI to increase the number of users reading notifications.

We need the ability to serve different experiments to different subsets of users.

See https://github.com/mixcloud/django-experiments.

**Comment by mathjazz** [comment]
Let's track this under #2272.
