### ISSUE TITLE
After search, clicking any field in the rich editor puts focus on the first field

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2287]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1704388](https://bugzilla.mozilla.org/show_bug.cgi?id=1704388)
Bug Reporter: @Archaeopteryx
CC:   @mathjazz

After a search for a string and finding it (string entity containing multiple properties/strings), a click into the edit field for any string will put cursor into first field.

Steps to reproduce: Search for `appmenu-update-manual2` and click into a different field than the first one. The cursor will be at the start of the first field. (A second string if you need to switch between strings: `appmenu-update-unsupported2`).

**Comment by mathjazz** [comment]
This should be fixed. Please reopen if the problem resurfaces.
