### ISSUE TITLE
Permissions: page is unusable when locale has many active contributors

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2289]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1708744](https://bugzilla.mozilla.org/show_bug.cgi?id=1708744)
Bug Reporter: @flodolo
CC:   @mathjazz

For example, go to the permissions for es-MX and try to search for an email. You can barely type a character that everything becomes incredibly slow
https://pontoon.mozilla.org/es-MX/permissions/

We should either have a delay after the user types something, or explicitly ask for enter?

**Comment by flodolo** [comment]
This is what I see in the log (besides a bunch of memory quota errors)

```
Mar 29 09:29:27 dyno=web.3 connect=0ms service=23872ms status=503 bytes=0 protocol=https
Mar 29 09:29:28 Process exited with status 137
Mar 29 09:29:28 State changed from up to crashed
Mar 29 09:29:28 State changed from crashed to starting
```

**Comment by Delphine** [comment]
Confirming that I can't load at all the Permissions page for (example) either zh-CN or fr locales. I'm trying to change permissions for zh-CN since they want to promote someone to manager, and someone else to translator

**Comment by flodolo** [comment]
> Confirming that I can't load at all the Permissions page for (example) in either zh-CN or fr locales

Sadly, you need to keep trying at different times. If you share the names on Slack, I might try at different hours than you.
Worst case scenario, we can fix it via Django admin :-(

**Comment by mathjazz** [comment]
There are two major sources of slowness:
1. The All users panel that lists all Pontoon users is always loaded.
2. The permission selector widget (which includes the All users panel) is loaded for each Project enabled for a Locale.

**Comment by mathjazz** [comment]
_Closed by mistake._

**Comment by mathjazz** [comment]
See also:
#2849
