### ISSUE TITLE
Tighten eslint and tsc configs to be strict

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2295]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1712449](https://bugzilla.mozilla.org/show_bug.cgi?id=1712449)
Bug Reporter: @Pike
Depends on:   [Bug 1685565](https://bugzilla.mozilla.org/show_bug.cgi?id=1685565)

The PR in bug 1685565 has pretty lax configs for tsc and eslint in the frontend config files.

We should tighten those towards strict, filing this bug to track that.

**Comment by eemeli** [comment]
TS config is tightened in #2439.
