### ISSUE TITLE
Add a badge to new users' avatars

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2309]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1728179](https://bugzilla.mozilla.org/show_bug.cgi?id=1728179)
Bug Reporter: @mathjazz

New users (users joined less than X days ago or users that have submitted less than X translations) should have a badge next to their avatar in the History panel, as an indication for reviewers to welcome them and give them guidance.

**Comment by mathjazz** [comment]
Superseded by #3393.
