### ISSUE TITLE
Error R12 in Update to Pontoon

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2311]
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1730077](https://bugzilla.mozilla.org/show_bug.cgi?id=1730077)
Bug Reporter: Woosuk Park &lt;<bjh13579@gmail.com>&gt;
CC:   @mathjazz

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0

Steps to reproduce:

so i upload to other things, pontoon is printed 'Error R12' and not uploading. so past upload, sometime (even 600 sec+), pontoon is hold on and upload success. but now, time is flowing, and pontoon is not sync message. so i need Postgredb edit program, and delete all the thing, and reupload to this.

Actual results:

upload is stopped, and R12 Message occur - Error R12 (Exit timeout) -> At least one process failed to exit within 30 seconds of SIGTERM

Expected results:

past, upload is completed.

**Comment by mathjazz** [comment]
This seems like a pretty big file on a low-power dyno. I assume this is the same as #2129.
