### ISSUE TITLE
Add ability to show project stats for a subset of teams

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2313]
Devs and PMs would like to see project stats for a subset of teams only, especially for projects we ship in several tiers of markets. This issue tracks the implementation of:

1. Ability to define subsets of teams in the project admin.
2. Ability to show project stats for each subset of teams.

In a followup, we'd also like to have the: 

1. Ability to switch between the subset(s) of teams and all teams in the project dashboard.
2. Reflect selected subset of locales in the Contributor and Insights tabs.

Mockup:
<img width="1059" alt="Screenshot 2021-09-20 at 15 55 18" src="https://user-images.githubusercontent.com/626716/134014557-2eed2ea3-a602-47b0-9018-e9d90a9b907a.png">

**Comment by flodolo** [comment]
> Ability to define subsets of teams in the project admin.

What if these could be passed as part of the URL? Is seem a lot more flexible, and might not require much more work in terms of implementation. I don't think you could expose that easily via UI, but maybe it's OK for such a feature to be half hidden?

**Comment by mathjazz** [comment]
That would actually be simpler implement, we could ship it pretty fast. @Delphine and I also talked about making the feature less visible.

@Delphine Would an URL like https://pontoon.mozilla.org/projects/firefox-for-ios/?locales=ar,zh-CN,fr,de,it,pl,sl (which would take you to the page shown in the mockup above) be sufficient, at least for the first iteration?

**Comment by mathjazz** [comment]
Deployed #2318 to stage:
https://mozilla-pontoon-staging.herokuapp.com/projects/firefox-for-ios/?teams=ar,zh-CN,fr,de,it,pl,sl
