### ISSUE TITLE
Labels overlap in DATE/TIME range picker

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2319]
<img width="320" alt="Schermata 2021-09-22 alle 11 02 29" src="https://user-images.githubusercontent.com/3644868/134317288-6a2608ee-ecb8-408c-ad7d-1d4cd22e055b.png">

Inspecting, the `transform="translate(80,0)"` seems to be at least 6 pixel (?) short. If I substract 6 pixel from the first two elements, it looks OK.

<img width="336" alt="Schermata 2021-09-22 alle 11 21 50" src="https://user-images.githubusercontent.com/3644868/134317844-2d23fc7b-a8d7-46b7-a0a4-98838486d1f4.png">

**Comment by nick-zanetti** [comment]
Can I have this assigned to me?
