### ISSUE TITLE
Add support for key-value JSON

### ISSUE THREAD

**Issue by Freebios** [mozilla/pontoon#2322]
Currently, Pontoon only supports WebExtension JSON files.
Key-Value JSON files seem to be used by people (including me :eyes:), adding support for them would be nice.

## Implementation

As it's been pointed out by @mathjazz on Mozilla chat, the key-value files parser could be selected seamlessly alongside the WebExtension one. Indeed files in WebExtension must be named `messages.json`.

The only constraint to use the key-value parser would be to use a filename different than `messages.json`. Additionally, we could fall back on the key-value parser if the `messages.json` structure could not be validated, but I guess this would lead to UX issues in case of structure error in an actual WebExtension file.

**Comment by 12rambau** [comment]
Any idea when this PR will be merged to the master branch? I don't really like the idea of relying on a personal fork of the project and I think this could super useful for many projects (e.g. anything based on the Symfony framework).

BTW: thank you @Freebios for your work !

**Comment by mathjazz** [comment]
Sorry @12rambau, it was me who dropped the ball on merging the PR. I just requested some changes there.

**Comment by Freebios** [comment]
This can be closed now :)

**Comment by mathjazz** [comment]
Thanks for the great work! 👍
