### ISSUE TITLE
Android-l10n: checks for improper placeholders

### ISSUE THREAD

**Issue by Delphine** [mozilla/pontoon#2323]
Localizers often submit improperly written placeholders, which in turns impedes string import on mobile side.
We would like that Pontoon notify localizers of these errors, and so that they can not submit them.

Example of placeholders:
%1$s
%s
%d
%2$s
%1$d

**Comment by mathjazz** [comment]
This bug should be addressed in compare-locales, which already checks for params in Android strings.

Thanks for Axel for sharing some links for reference:
https://github.com/Pike/compare-locales/blob/master/compare_locales/checks/android.py#L194
https://github.com/Pike/compare-locales/blob/master/compare_locales/tests/android/test_checks.py

@eemeli Have you perhaps given any thoughts to compare-locales yet? It's currently hosted on hg.mozilla.org, with a (slightly out-of-date) mirror on [GitHub](https://github.com/Pike/compare-locales). I guess the good first step would be to move the official repo to GH, possibly under the `mozilla` org.

**Comment by keunes** [comment]
Does compare-locales give direct feedback to the translator?

**Comment by mathjazz** [comment]
Yes, compare-locales is integrated into Pontoon. Every time a translation is submitted, several checks are engaged, including the ones provided by compare-locales.

https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/translate.html#quality-checks
