### ISSUE TITLE
Add 'yarn install' to the frontend build process

### ISSUE THREAD

**Issue by abowler2** [mozilla/pontoon#2324]
When setting up a new development environment the node modules are not created with the build process. 

In order to minimize friction for new contributors getting set up we should include `yarn install` in the build process.

**Comment by mathjazz** [comment]
The root issue here is that code editors don't have access to containers, where the build process takes places (including execution of `yarn install`), which makes the development experience suboptimal (import errors, no IntelliSense support...).

Running `yarn install` on the host system as part of the build process solves half of the problem. The other half is the installation of python packages. I wonder if that's overwhelming.

Axel found https://code.visualstudio.com/docs/remote/containers, which we could point to as an alternative solution to the problem. The obviously drawback is that this is an editor-specific solution and while most of us use VSCode, I don't think any of has tried how the solution works in practice.
