### ISSUE TITLE
Deploy to Heroku - 'CSRF_USE_SESSIONS is enabled, but request.session is not set' error

### ISSUE THREAD

**Issue by tec1106** [mozilla/pontoon#2346]
I used to 'Deploy to Heroku' button but when I try to access the app after deployment I get a 500 Server error. In the logs I find: 
"CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE."

I tried my best, but I have no idea how to fix it.

**Comment by mathjazz** [comment]
Thanks for the report!

Confirming I can no longer deploy using "The Purple Button". If I click it on https://github.com/mozilla/pontoon/, the Heroku Deployment page doesn't even finish loading. Do you get beyond that point?

**Comment by mathjazz** [comment]
I am able to deploy from the docs though, where we list the template explicitly:
https://mozilla-pontoon.readthedocs.io/en/latest/admin/deployment.html

And I can't reproduce your error. Did you set `SITE_URL` to `https://{app-name}.herokuapp.com`?

**Comment by mathjazz** [comment]
Let's close and track the reproducible problem with the Heroku deploy button in #2460.
