### ISSUE TITLE
Links below time range graph (7D, 1D, 24H, etc.) are missing

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2350]
Not exactly sure when it happened, but right now there's an empty space under the time range graph.

<img width="347" alt="Schermata+2021-10-31+alle+06 57 39" src="https://user-images.githubusercontent.com/3644868/139577629-4088aa0d-ac24-4175-a0da-90c5b864817b.png">

**Comment by mathjazz** [comment]
See also #2319.

**Comment by mathjazz** [comment]
Is this one still reproducible?

**Comment by flodolo** [comment]
No, labels are back, still problems with the overlap.
