### ISSUE TITLE
Incorrect docker-compose.yaml version number

### ISSUE THREAD

**Issue by Dazag** [mozilla/pontoon#2372]
If you try to _docker-compose up -d_ or _make build_, docker will inform you that the **target:** property can not be used in that context. The specified docker-compose version is 2, but **target** property wasn't available until 2.4. I can confirm that after setting the version number to 2.4, the containers were recreated succesfully

**Comment by eemeli** [comment]
Huh, you're right. Odd that this hasn't caused errors in our builds. It looks like [`version: '2.3'`](https://docs.docker.com/compose/compose-file/compose-versioning/#version-23) is the least that's required.

@Dazag Would you like to submit a PR fixing this?

**Comment by Dazag** [comment]
Sure I would love to, let me create the PR.
