### ISSUE TITLE
"Copy" does not copy variables for fluent 

### ISSUE THREAD

**Issue by bidaian** [mozilla/pontoon#2374]
Take [this FTL string](https://pontoon.mozilla.org/eo/firefox/all-resources/?string=233939), the original is:

![bildo](https://user-images.githubusercontent.com/378695/143667384-cda8b5c7-4636-4b1f-8f82-f3834b7b9c65.png)

but after "Copy" this is shown (note that the variables are missing):

![bildo](https://user-images.githubusercontent.com/378695/143667424-cedd57d1-b807-49e6-a00c-1ccad2adfa8d.png)

although switching to the FTL editor will show the whole text:

![bildo](https://user-images.githubusercontent.com/378695/143667378-641fc349-0b55-42cd-8113-ed064087ddea.png)

I'm running Firefox 94.0.2 on Linux. This happens, for me, with "Copy" for all FTL strings with variables. This is [another example](https://pontoon.mozilla.org/eo/firefox/all-resources/?string=192290).

**Comment by flodolo** [comment]
Adding here, even if only partially related: COPY now seems to copy only partial strings for plurals (reported on Matrix)

Try on this string: https://pontoon.mozilla.org/en-GB/all-projects/all-resources/?string=236126

Did we touch this code recently? Both used to work without issues.

**Comment by mathjazz** [comment]
The culprit is #2367. @eemeli Do you have cycles for this?
