### ISSUE TITLE
Pontoon showing empty diff and not submitting new translation

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2401]
https://pontoon.mozilla.org/ar/firefox/browser/browser/aboutPocket.ftl/?search=pocket-panel-signup-signup-firefox&string=224278

I've tried to edit the string offline (in a text editor), since compare-locales was complaining for a missing term.
* Pontoon's diff doesn't show anything
* Pontoon doesn't seem to commit this string to [the repository](https://hg.mozilla.org/l10n-central/ar) (there were already 2 syncs, no commit)

**Comment by flodolo** [comment]
I think the only difference is that the last string has a newline at the end, so that would explain the empty diff. Still, why does Pontoon accept the translation as new, but doesn't commit it?

The side question would be to understand what triggers compare-locales…

**Comment by mathjazz** [comment]
I am unable to submit translations with the only difference being newline at the end. Is this still an issue?

**Comment by flodolo** [comment]
I haven't hit this in a while.

**Comment by mathjazz** [comment]
Let's reopen or file a new issue if the problem resurfaces.
