### ISSUE TITLE
Search is broken in Pontoon documentation

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2404]
I pointed it out on Matrix a while ago, but I don't think anybody looked into it.

https://mozilla-pontoon.readthedocs.io/en/latest/search.html?q=sync&check_keywords=yes&area=default

Search has been broken for at least a month, not sure whose fault that is (Pontoon or Read the Docs).

**Comment by Pike** [comment]
I did look back then, and it's a bug in the theme. But I also don't know if this is RTD's fault or ours. I had a look at their source and didn't find any related changes. But then again, I also don't have access to RTD for Pontoon, so I couldn't check when we last updated the docs.

Maybe just a rebuild could fix this.

**Comment by mathjazz** [comment]
Thanks for looking into it!

Rebuild does not help (just triggered a build by merging a PR).

I can search on the [project page](https://readthedocs.org/projects/mozilla-pontoon/search/).

**Comment by mathjazz** [comment]
Thank you, [dependabot](https://github.com/apps/dependabot) (https://github.com/mozilla/pontoon/pull/3141).
