### ISSUE TITLE
Plural textareas are small by default

### ISSUE THREAD

**Issue by SafaAlfulaij** [mozilla/pontoon#2406]
By default, when opening a plural string, the textareas are one-row-area, and the user needs to increase the height of each manually.

Normal string:
![image](https://user-images.githubusercontent.com/3509617/149460941-b8617635-b6d4-4a9a-88c2-30bd49dbc445.png)

Plural string:
![image](https://user-images.githubusercontent.com/3509617/149460970-736f3d88-b27b-4e76-b994-5cf5fda3a4cd.png)

I'd say to have a minimum of two text rows per textarea.

**Comment by mathjazz** [comment]
Thanks for the report! This is a similar issue to the one reported in https://github.com/mozilla/pontoon/issues/2274, so let's continue there.
