### ISSUE TITLE
Failed Compile after Machinery.tsx change 

### ISSUE THREAD

**Issue by readingsnail** [mozilla/pontoon#2410]
So, Change to Since Fix #2388 - Refactor Machinery.tsx to functional (#2391), Heroku has not making Compiling.

Failed to compile.
./src/modules/machinery/components/Machinery.tsx
Attempted import error: 'Translation' is not exported from './Translation'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Collecting static files...
bin/post_compile: line 22: ./manage.py: No such file or directory
bin/post_compile: line 23: ./manage.py: No such file or directory
Current commit being deployed: 
af474fbf49e4149f8edbff4de1ed7b70392c1fd9
bin/post_compile: line 30: static/revision.txt: No such file or directory

-----> Discovering process types
       Procfile declares types -> web, worker
-----> Compressing...
       Done: 246.5M
-----> Launching...
       Released v160

**Comment by mathjazz** [comment]
Thanks for the report. It doesn't ring a bell on a very first look. Do you get the same error with d26999eea57902a30b5c15e9b77277fe7e76a60f?

**Comment by readingsnail** [comment]
Yeah, it's same [d26999e](https://github.com/mozilla/pontoon/commit/d26999eea57902a30b5c15e9b77277fe7e76a60f) merge. 

v158(intial change Machinery.tsx) -> rollback(v159) -> v160 -> rollback(v161) is same
Creating an optimized production build...
Failed to compile.
./src/modules/machinery/components/Machinery.tsx
Attempted import error: 'Translation' is not exported from './Translation'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Collecting static files...
bin/post_compile: line 22: ./manage.py: No such file or directory
bin/post_compile: line 23: ./manage.py: No such file or directory
Current commit being deployed: 
b9e99498d2e1bdad76b03eeff58c61d34a752fec
bin/post_compile: line 30: static/revision.txt: No such file or directory
-----> Discovering process types
       Procfile declares types -> web, worker
-----> Compressing...
       Done: 246.4M
-----> Launching...
       Released v158

**Comment by mathjazz** [comment]
Hey @readingsnail, we are unable to reproduce your issue when building locally with Docker or when deploying to Heroku.

Could you please explain how your deployment setup looks like?

**Comment by readingsnail** [comment]
Sorry for inconvenience, replace frontend folder of official repo, it's completed.
