### ISSUE TITLE
Refactor EntitiesList.tsx to a function component

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2412]
Motivation is the same as with https://github.com/mozilla/pontoon/pull/2391.

Switching to https://github.com/onderonur/react-infinite-scroll-hook would let us unify the infinite scroll code with the one used for Concordance search, which was introduced in https://github.com/mozilla/pontoon/pull/2394.

**Comment by yaya-usman** [comment]
Hey @mathjazz please can i get assigned this issue?

**Comment by mathjazz** [comment]
Sure, it's done. :)

**Comment by yaya-usman** [comment]
@mathjazz  Thanks.
