### ISSUE TITLE
Rename "Deadline"

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2434]
As part of https://github.com/mozilla/pontoon/pull/1565, we wrote that "Deadline sounds permanent, threatening, and ugly."

Let's replace the word with something else.

Maybe "Due date"?

**Comment by flodolo** [comment]
What about `Target date`?

**Comment by Delphine** [comment]
I'm all for "target date"

**Comment by Delphine** [comment]
I also liked "milestone" because it did convey something that was ongoing in time.
