### ISSUE TITLE
where can I find the language list in the code ? 

### ISSUE THREAD

**Issue by 12rambau** [mozilla/pontoon#2436]
I'm building an app that will be translated with Pontoon. The developers will have the possibility to opt-in new languages. To avoid people requesting language that makes no sense, I would like to use the list that is used by pontoon in the main interface. 

Is this list available somewhere in pontoon files or is dynamically updated? Can you show me where to look?

**Comment by mathjazz** [comment]
Hey @12rambau,

The initial list of locales is accessible and editable in the Django Admin at /a/base/locale/.

Please note that the best place to ask support questions is Discourse:
https://discourse.mozilla.org/c/pontoon/

**Comment by 12rambau** [comment]
thanks for your answer and sorry for the noise
