### ISSUE TITLE
Broken heroku deploy button

### ISSUE THREAD

**Issue by Goddino-Repo** [mozilla/pontoon#2460]
When i try to deploy pontoon on heroku, i got an infinite charge..
![image](https://user-images.githubusercontent.com/39674510/159341794-4393827a-5b36-49b7-89b4-52b9602d1e72.png)

I just clicked on button from README file and logged in to heroku platform

**Comment by mathjazz** [comment]
Thanks for reporting!

Could you please confirm that you can deploy from the button in the docs?
https://mozilla-pontoon.readthedocs.io/en/latest/admin/deployment.html

**Comment by mathjazz** [comment]
You mean Heroku login or Pontoon login?

If Pontoon, you need to create an admin account first:
https://mozilla-pontoon.readthedocs.io/en/latest/admin/deployment.html#creating-an-admin-user

**Comment by Goddino-Repo** [comment]
Ok Thanks, there was my mistake

**Comment by mathjazz** [comment]
The issue with the Heroku Deploy button in the repository is still a valid issue.

**Comment by jamesking** [comment]
I came across this problem too. When I use the button, I get taken to the Heroku `Create New App` page, which loads UI, but no resources show in the `Resources` section of the page and the `Add to pipeline…` button does nothing.

![CleanShot 2023-03-14 at 14 11 33@2x](https://user-images.githubusercontent.com/11338/225029391-773667b3-553a-4f0d-acb9-53a0a4a13d50.png)

There are some errors in the JS console for the Heroku site which makes me think this is a Heroku issue. 

<img width="800" alt="CleanShot 2023-03-14 at 14 16 37@2x" src="https://user-images.githubusercontent.com/11338/225029579-28b69b81-1fe7-45f8-bde0-b74898bfc179.png">

**Comment by mathjazz** [comment]
Confirming I can reproduce the issue.

Workaround with using the button on https://mozilla-pontoon.readthedocs.io/en/latest/admin/deployment.html#creating-an-admin-user is no longer possible.
