### ISSUE TITLE
Error when navigating string list using keyboard shortcut very fast

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2461]
STR:
1. Go to [translate view with an active search term](https://mozilla-pontoon-staging.herokuapp.com/sl/amo/all-resources/?search=count).
2. Hold Alt + Down (hold both keys!) to move down the entity list very fast.

Expected result: Selected strings should open in the editor.

Actual result: The page crashes with "TypeError: history.translations.find is not a function".

**Comment by eemeli** [comment]
This was fixed by #2479.
