### ISSUE TITLE
Buggy teams

### ISSUE THREAD

**Issue by Goddino-Repo** [mozilla/pontoon#2462]
- Teams tab:
![image](https://user-images.githubusercontent.com/39674510/159541550-1064b79b-88fe-4011-885a-bc7c0750fcfc.png)
Error

- Projects teams tab:
![image](https://user-images.githubusercontent.com/39674510/159541725-4a534a87-5c05-4dc4-a50b-31d28bc3a818.png)
4 teams but empty list

- Setting a custom language as custom homepage:
![image](https://user-images.githubusercontent.com/39674510/159541968-86e3cf01-9de5-495e-a9ca-2395cdda1125.png)
Got an error when i try to go to homepage:
![image](https://user-images.githubusercontent.com/39674510/159542229-9a64040a-9ff4-4f82-80b9-8e4a4700a907.png)
Look at the URL -> https://im-translations.herokuapp.com/ **pontoon.teams.team**

**Comment by mathjazz** [comment]
Could you please provide the steps to reproduce?

**Comment by Goddino-Repo** [comment]
Hi @mathjazz 
Just click on "Teams" tab

Or if you mean teams tab for a project...
Go to the main dashboard from the site root, click on projects, select one project, you will see "Teams" tab without a list
I tried to do the same thing on the official pontoon by mozilla, and in projects team tab i saw all available languages

But in my pontoon instance, i see 4 teams but actually I can't navigate a language

This is my instance:
Https://im-translations.herokuapp.com/

**Comment by mathjazz** [comment]
Sorry, lost track of this completely. 😐 

Please reopen if this is still relevant.
