### ISSUE TITLE
Run make format and make lint in relevant folders only

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2468]
Currently `make format` and `make lint` commands spend most of the time formatting and linting files in the `/static` and `/media` folders, which are not even committed to the repository.

Ideally, we should only run these two commands (and the commands they call into) on the actual source files (in `/pontoon`, `/translate` and  `/tag-admin` folders).

**Comment by Pike** [comment]
Maybe it makes sense to set up lint-staged, too?
