### ISSUE TITLE
Broken UI and errors in Fluent string with empty attribute

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2470]
Here's the string
https://pontoon.mozilla.org/hye/firefox/browser/browser/places.ftl/?search=places-open-in-container-tab&string=243435

My checks were triggered, because Pontoon [committed](https://hg.mozilla.org/l10n-central/hye/rev/50466e3014a2138a412911a131aa4043cf8cbbd5) a non parseable entity to hg

```
places-open-in-container-tab =
    .label = Բացել նոր ներդիրում
    .accesskey = 	
```

I'm not sure how the localizer got there, but now Pontoon breaks in all possible ways:
* Switching to FTL mode, then back, will hide the input fields.
* Trying to reject or approve the translation will result in a blank page.

**Comment by mathjazz** [comment]
Looks like there's a tab in the `accesskey` value, which allowed the user to submit a broken string in first place.

**Comment by mathjazz** [comment]
So the string contains a tab character, but it gets removed when we serialize the string to VCS or to show it in the source editor.

@eemeli Does that look like a bug in python-fluent?

```python
from fluent.syntax import ast, FluentParser, FluentSerializer
parser = FluentParser()
serializer = FluentSerializer()

string = """places-open-in-container-tab =
    .label = Բացել նոր ներդիրում
    .accesskey =
"""

string
'places-open-in-container-tab =\n    .label = Բացել նոր ներդիրում\n    .accesskey = \t\n'

serializer.serialize(parser.parse(string))
'places-open-in-container-tab =\n    .label = Բացել նոր ներդիրում\n    .accesskey = \n'
```

**Comment by eemeli** [comment]
Yes, that looks like a python-fluent bug. According to the [spec](https://github.com/projectfluent/fluent/blob/master/spec/fluent.ebnf), only spaces are included in `blank_inline`, and effectively tabs should be considered here as `inline_text`, i.e. a part of the message's value.

**Comment by Pike** [comment]
The syntax js parser in the playground also doesn't show the tab as part of the TextElement.

**Comment by mathjazz** [comment]
Seems like recent updates to the editor have fixed the Pontoon side of the issue. 👍

@eemeli Do we track the `python-fluent` part somewhere?

**Comment by eemeli** [comment]
@mathjazz This has been fixed in `python-fluent`, but hasn't yet been included in a release of it. That's currently blocked by waiting for projectfluent/python-fluent#180 to land. If you feel like reviewing that we could get this forward... 😇
