### ISSUE TITLE
Make review notification sound less discouraging

### ISSUE THREAD

**Issue by upwinxp** [mozilla/pontoon#2471]
We have implemented a notification to alert localisers of their reviewed translations, which gives the number of approved and rejected translations. If a reviewer slightly modifies a contributor's translation before approving the modified version, the contributor's translation is considered "rejected", which might sound quite discouraging. I suggest to reword the notification not to mention "rejected" strings - for example, "6 of 10 approved" or simply "10 reviewed".

**Comment by flodolo** [comment]
Personally, I think it's important to know if my translations were rejected. Using a different term would potentially create confusion, given that's what the UI does.

**Comment by mathjazz** [comment]
What if we just show the review count? You need to click anyways to see which translations got rejected and which got approved.

**Comment by flodolo** [comment]
I don't need to click if all translations were approved. So, that would be counterproductive for me.

**Comment by mathjazz** [comment]
That's a good point - @upwinxp what are your thoughts on this?

Note that we also have #2356 (and #2357), which is about tracking review edits as separate actions in general (not just notifications). Maybe that's a more proper fix, and once done, we can also make review notifications more specific (i.e. 6 approved, 3 edited and 1 rejected)?

**Comment by mathjazz** [comment]
OK, thanks. Let's close this issue then and continue in #2356.
