### ISSUE TITLE
Enter-key event submits translation without accepting IME candidates first

### ISSUE THREAD

**Issue by petercpg** [mozilla/pontoon#2476]
## STR
1. Open Pontoon, go to any translation
2. Enter translation for the string using [IME](https://en.wikipedia.org/wiki/Input_method) (just type some random words, do not hit Enter yet)

## Expected
1. After correcting candidate words in the IME buffer, the content in IME buffer is cleared and inserted to translation field on Pontoon, but the translation was not submitted to Pontoon yet
2. Hitting another Enter or by clicking Save (when there no IME typing occur) submits the translation

## Actual
1. Hitting Enter inserts current buffer, and the translation is submitted to Pontoon altogether

## Environment:
* Microsoft Windows 11 21H2 22000.556
* Firefox Nightly 101.0a1 (2022-04-17) (64 bit)
* Both OS and Firefox locales are in zh-TW
* Only tested with Microsoft Phonetic (for zh-TW) / Microsoft IME (for ja) and it reproduces with both IMEs.

**Comment by mathjazz** [comment]
Seems related to #2475. Both issues were likely caused by #2444.

**Comment by mathjazz** [comment]
@eemeli Will you have cycles to look into this tomorrow?

**Comment by petercpg** [comment]
Testing with latest Relay website strings, I can confirm this issue is now gone in production.
