### ISSUE TITLE
Allow user to add a contact email address

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2482]
Reference: [specs](https://github.com/mozilla/pontoon/blob/master/specs/0111-redesign-profile-page.md)

Users should be able to provide a contact email address that will be displayed in the profile page (pending personal visibility settings). If not provided, the email address associated to the account used to log in to Pontoon will be displayed.

The email address of managers and administrators will always be visible to logged in users, since contributors need to be able to contact them.

Blocked by:
* #2481

**Comment by mathjazz** [comment]
Implementation note: we should verify email addresses before saving them.
