### ISSUE TITLE
Allow user to set a vanity URL for their profile

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2483]
Reference: [specs](https://github.com/mozilla/pontoon/blob/master/specs/0111-redesign-profile-page.md)

In order to share a profile more easily, users should be able to set up a vanity URL — a unique identifier, easier to remember, that can be used in the URL instead of the random ID assigned by Pontoon.

**Comment by mathjazz** [comment]
@flodolo @eemeli We should finish the discussion started in the [brainstorming doc](https://docs.google.com/document/d/1swnj1MwG9vCXC7X1bP60o0asAVADIgau2TLQ4nQy_ww/edit#bookmark=id.gfwb82d7n55a): whether the user should set aa `vanity_url` or a `username` field.

My take: it should be a username, because that's consistent with popular platforms. It also allows us to use that field in other places, e.g. user presentation in the UI when (Display) Name not set and in user mentions (where display name is causing problems due to spaces).

**Comment by flodolo** [comment]
I'm still of the idea that the profile URL should be a separate thing from the username (and we'd benefit from the latter in mentions). 

The counter-example, talking about popular platforms, is LinkedIn, where you can set your own vanity URL.

**Comment by mathjazz** [comment]
AFAICT, there's no concept of username in LinkedIn. Which makes sense - they are a professional networking site, and job seekers want to be identified with real names and photos. So Profile URL is the only option for them.

It's not exactly the same on Pontoon. Many of our users don't give away their real identify, as we can see by their display names and avatars. So having a username makes sense. And when you have it, why have a separate URL field?

Exposing all three fields (display name, username and a custom profile URL) would be quite unique and quite complex to reason about.

**Comment by flodolo** [comment]
> It's not exactly the same on Pontoon. Many of our users don't give away their real identify, as we can see by their display names and avatars. So having a username makes sense. And when you have it, why have a separate URL field?

As explained in the original conversations, if the idea is to use this profile URL to promote yourself professionally, you might not want to use the username you use internally (`unclenachoduh` would be a good example, but even `flod`).

**Comment by mathjazz** [comment]
We'd still show `unclenachoduh` on the profile page if we introduce usernames, so having a different URL wouldn't really prevent the potential embarrassment. :)

I also assume a very small minority would use a profile URL that is different than a username, and the remaining vast majority would be confused.

**Comment by flodolo** [comment]
Fair point. 

With that said, I'm not going to be convinced that having two separate fields is a bad idea, because I only see pros from the user perspective, even if it might only benefit a subset (and I also don't see how that would be confusing). But I will accept your decision on what to implement.

**Comment by mathjazz** [comment]
Thanks. Opened #2594.

**Comment by eemeli** [comment]
I'd prefer starting off with a single "username" that's used only in the vanity URL, because that's conceptually simpler and avoids us needing to set up two interconnected namespaces.
