### ISSUE TITLE
Add filters for contribution graph

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2485]
Reference: [specs](https://github.com/mozilla/pontoon/blob/master/specs/0111-redesign-profile-page.md)

To implement the contribution graph, we need to be able to link to new filtered views:
* Reviews performed by user
* Reviews received by user

Once implemented, the latter should also be used for review notifications.

**Comment by mathjazz** [comment]
There are 3 types of activities tracked by the [Contribution Graph](https://github.com/mozilla/pontoon/blob/master/specs/0111-redesign-profile-page.md#contribution-graph):

1. **Submissions**: translations submitted by the user.
2. **Reviews performed**: reviews performed by the user.
3. **Reviews received**: reviews from other users, performed on suggestions submitted by the user.

We can filter these actions using the following filters:
1. `author` + `time`
2. **`review_author`** + **`review_time`**
3. `author` + **`review_time`**

Which means we need 2 new filters:
1. `review_author`
2. `review_time`
