### ISSUE TITLE
Approval through mass action should reject other suggestions

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2505]
I've used for the first time the mass approval feature, and I find it very surprising that it didn't reject the other pending suggestions.

The approval action should be consistent to the single-string scenario: you approve one translation, you automatically reject the other suggestions.

**Comment by mathjazz** [comment]
Unlike in a single action scenario, where you have all the suggestions in front of you, you don't see the suggestions you will reject by a batch action. You could reject an even better suggestion than the active one that way.

If you are 100% sure you know what you are doing, there's Reject All Suggestions action, which is just a click away.

**Comment by flodolo** [comment]
So, the idea is that you first approve all, then reject all suggestions that remain? 

That seems counterintuitive to me, but I can live with that, as long as it's [documented](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/translate.html?highlight=mass%20action#performing-batch-actions-on-strings) (which reminds me, we completely lost track of revamping Pontoon's user documentation…).

**Comment by mathjazz** [comment]
The way I use it is to mass approve all by comparing the source string and the translation in the string list.

If there are any suggestions that remain, I go through them one by one.

**Comment by flodolo** [comment]
The way my team works is that:
1. A translator does the first pass, putting everything as suggestion.
2. Reviewer approves or puts an alternative, then ask for feedback to the translator.
3. If the translator doesn't have any objection, the alternative version gets approved (and they're always the first of suggestions).

I normally go by one by one, but this time I had ~20 and decided to use mass approval, and that doesn't work as I was expecting.

**Comment by mathjazz** [comment]
In such scenario I agree rejecting suggestions in a separate step is unnecessary.

I doubt many teams follow such pattern, though. At least there aren't any indications they do.

So I'd rather stay on the safe side and avoid losing suggestions that have never been seen by the reviewers. Additional click is a small price to pay for that.

**Comment by flodolo** [comment]
Sounds good to me.
