### ISSUE TITLE
After sending a comment, the text remains in the input field

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2519]
Type a comment and send it. The text will then be displayed again in the input field, below the comment just sent.

I'm pretty confident this is a regression.

**Comment by eemeli** [comment]
Yeah, this appears to be due to an upstream change: ianstormtaylor/slate#4612. We'll need to add a workaround for it.

**Comment by mathjazz** [comment]
Ouch. I broke that in https://github.com/mozilla/pontoon/commit/03435d9283d78de2405279e5cb289bb8bf13e343, which was a security update.

@eemeli Do you want to look into it?

**Comment by mathjazz** [comment]
Relatedly, I also noticed that the comment input field is now too wide. On macos horizontal scrollbar appears briefly, and I guess it's always visible in other OSes.
