### ISSUE TITLE
Missing link in comment notifications when string gets deleted

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2538]
I can't tell if this was a temporary issue, or something else, but I noticed some of my notifications miss a link to jump to the string with a comment.

I edited the screenshot to remove other comments, but here you go

<img width="657" alt="Schermata 2022-05-25 alle 08 20 44" src="https://user-images.githubusercontent.com/3644868/170194325-af8bed79-02b4-4361-9d30-683f0c56262b.png">

Maybe it's the type of comment (translation vs source string)?

**Comment by mathjazz** [comment]
Hm, I can't find these comments in the DB.

**Comment by flodolo** [comment]
> Hm, I can't find these comments in the DB.

Uh, maybe the string was removed recently, and Pontoon is smart enough to not show a broken link?

**Comment by flodolo** [comment]
If I remember correctly, the comment was on this string, which was indeed removed a week ago
https://mozilla-pontoon-staging.herokuapp.com/tg/firefox/toolkit/chrome/mozapps/downloads/unknownContentType.dtd/?string=80020

**Comment by mathjazz** [comment]
We should reformat the message (at least drop the "in").
