### ISSUE TITLE
"Age un unreviewed" graph in locale insights is empty

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2559]
https://pontoon.mozilla.org/it/insights/

Switch to "Age of unreviewed", the graph is empty. Nothing is reported in the console.

**Comment by mathjazz** [comment]
I see this:

<img width="455" alt="Screenshot 2022-07-02 at 11 18 54" src="https://user-images.githubusercontent.com/626716/176994496-b278924a-0381-4a67-a4d0-6518d0ad42d1.png">

**Comment by flodolo** [comment]
Interesting, I see this 

![Schermata 2022-07-02 alle 12 26 35](https://user-images.githubusercontent.com/3644868/176996741-8b89a457-ca5e-4625-8d72-7e723b68792e.png)

I tried disabling likely culprits (uBlock, Tracking protection), but no change. I also get the same result in Private Window.

**Comment by flodolo** [comment]
I also see the empty graph on release, with a clean profile, and even with Chrome. I guess we need a third person…

**Comment by eemeli** [comment]
Same (correct) results as @mathjazz for me, using Firefox Nightly. Logging in/out does not change the outcome for me.

**Comment by flodolo** [comment]
Still broken for me, even tried using en-US in my release profile 🤷🏼

**Comment by flodolo** [comment]
I've tried with a VPN, same issue. Since it happens in private mode and a clean profile, it's not tied to the account either.

At this point, not sure what else it could be.

**Comment by mathjazz** [comment]
What's your screen resolution?

Does the 2nd graph div jump up if you bump the width of `#insights .suggestions-age-items` for a few pixels (e.g. 941px or 950px)?

**Comment by flodolo** [comment]
Yes, macOS. 

One interesting find: if I look at the page on the MacBook screen (14" retina), it's displayed correctly. But it's not displayed on my external monitor (2560x1440). If I open the page on the integrated screen, then move it, it stays displayed.

I need to bump the width over 1035px to see a bit of the graph, as the two divs are 470px and 565px wide. When I look at the page generated on the integrated screen, the second div is only 470 (410 + 60 padding right).

**Comment by mathjazz** [comment]
I can reproduce on an external screen if I set resolution to native.

**Comment by mathjazz** [comment]
Fixed in #2565.
