### ISSUE TITLE
Clicking item in MACHINERY doesn't focus the translation area

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2573]
I'm confident that, before, I could click an element in MACHINERY and press enter to confirm. Now, I need to click the SAVE button with the mouse, or manually give focus to the translation area.

**Comment by mathjazz** [comment]
I just tried that with a couple of strings and couldn't reproduce. Could you provide an example?

**Comment by flodolo** [comment]
OK,  I see what happened 🤦🏼 

It only happens when there's a 100% match and the content is pre-filled ([example](https://pontoon.mozilla.org/ta/firefox/all-resources/?extra=missing-without-unreviewed&string=237850)). Clicking the element in machinery hides the banner, but doesn't give focus to the text area.
