### ISSUE TITLE
Site isn't compatible with dark mode

### ISSUE THREAD

**Issue by Aikatsui** [mozilla/pontoon#2576]
Steps to enable: chrome://flags/ --> search "dark mode" --> auto dark mode for web contents --> enable

Another rare site :/
![image](https://user-images.githubusercontent.com/63988538/180327872-b4caf320-6003-435e-be32-893f2e65b8e0.png)

**Comment by Aikatsui** [comment]
https://github.com/mozilla/pontoon/issues/2141

**Comment by Aikatsui** [comment]
Note: homepage only

**Comment by mathjazz** [comment]
Thanks for reporting!

I'm not exactly sure if this is a bug in Pontoon or in Chrome. Pontoon already uses a dark theme, so one would expect Chrome knows how to deal with it.

Besides, it's an experimental feature. I haven't found feature documentation yet, which we'd need to understand how it works and how to debug it.

**Comment by Aikatsui** [comment]
It's not chrome bug. May be you can check how other site works. i don't know about UI / UX
See https://gridsome.org/ (you can toggle dark / sepia / light and check)

>Pontoon already uses a dark theme

The problem, it isn't compatible or doesn't work with that.

**Comment by mathjazz** [comment]
I would argue that this is a bug in Chrome:
https://developer.chrome.com/blog/auto-dark-theme/#per-element-customization

Since the way around if not too difficult on our end, I've created a PR to force Pontoon to ignore the Auto Dark Theme theme (#2579).
