### ISSUE TITLE
Can’t upload translations

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/pontoon#2577]
Hi,

It looks like the ”Upload translations” option is missing when opening any file in any project. I’m using the feature primarily to publish content translated by vendors

<img width="487" alt="Capture d’écran 2022-07-25 à 12 40 26" src="https://user-images.githubusercontent.com/1294206/180758519-38bc27e7-453a-490e-bc01-d4a4dc91831f.png">

**Comment by mathjazz** [comment]
@eemeli Seems like a regression from #2576. Do you want to take it?

For some reason the `entity` object [here](https://github.com/mozilla/pontoon/blob/master/translate/src/core/user/components/UserMenu.tsx#L39) always represents the initial entity instead of the actual one.
