### ISSUE TITLE
Delay before contact person data appears in the comment field

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2591]
Since #2588, there is now a short delay after clicking "REQUEST CONTEXT or REPORT ISSUE" before the contact person's data is entered into the edit field due to the mention data loading in the background.

**Comment by eemeli** [comment]
The right fix here would be to change the `/get-users/` API to filter the results. Atm, it's sending data on _all_ the users, and on pontoon.mozilla.org that's currently compressing down to about 900kB, which obviously takes a while to transfer.

As we only use this for the comment `@`-mentions, we probably shouldn't cache the data in the client at all, and instead work with some much smaller subset matching a query.

It might be possible to work around the #2834 issue separately by using a stand-in for the contact person's mention before all the data is available.
