### ISSUE TITLE
No warnings when trying to submit empty translations

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2599]
I've noticed an increase in the number of empty strings in Firefox, where I have [special checks](https://test.flod.org/checks/).

Apparently, we don't warn anymore when someone tries to submit an empty translation.

**Comment by mathjazz** [comment]
Is that Fluent specific? We should submit `{ "" }` as an empty translation, which was indeed [introduced recently](https://github.com/mozilla/pontoon/pull/2534).

Is that not the case? What is the expectation?

**Comment by flodolo** [comment]
The expectation is to get a warning, not submit directly. Wasn't that the case before?

**Comment by mathjazz** [comment]
I think we prevented submission completely, because the actual empty string was being submitted, which is an error in Fluent.

**Comment by flodolo** [comment]
Note: this is starting to impact other Fluent projects, so it's clear to me that we changed the behavior.

**Comment by eemeli** [comment]
Starting to properly look at this. The proximate cause of this is the way that we no longer construct broken Fluent messages for empty content, so solving the issue will likely require a compare-locales update.
