### ISSUE TITLE
Consider replacing "last month" text with "last 30 days"

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2623]
By default, the activity log shows data from the last 30 days, with a label saying "last month". But that's highly ambiguous in English ([example](https://forum.wordreference.com/threads/in-the-last-month-vs-last-month.3272532/)).

A more accurate "last 30 days" wouldn't leave any space for interpretation.

**Comment by flodolo** [comment]
> But we also have "in the last year" above the contribution graph.

That means "In the current year" though, not in the last 365 days? We should probably update that as well…

**Comment by mathjazz** [comment]
No, the chart shows 365 squares.

**Comment by flodolo** [comment]
Why did I remember a graph only showing the current year? 🙄 

I see GH has the same approach on that (365 days = last year). Maybe it's just be being confused by English.

**Comment by mathjazz** [comment]
As part of #2619, we could also add "Last year" as one of the year selectors. That should make it clearer what last year means. And then it should be also clearer what last month means.

Note that "last 30 days" is not always correct. See "[How does it handle months with different numbers of days?](https://dateutil.readthedocs.io/en/stable/relativedelta.html)".

**Comment by flodolo** [comment]
OK, let's close this, since the confusion seems to be mostly on my side ;-)
