### ISSUE TITLE
String comment input field gets focus after approving a translation

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2626]
Pre-condition: have multiple suggestions pending for review.
* Click on the COMMENTS tab in the top right.
* Click on the input field for translation, press Enter to save.

At this point, Pontoon moves to the next string, but the focus goes to the input field in the COMMENTS tab, instead of staying in the translation area.

**Comment by mathjazz** [comment]
@eemeli Could you have a look at this one?

**Comment by mathjazz** [comment]
Bumping priority to P2.
