### ISSUE TITLE
[Bug] Suggest anyway button overlapping check message in portait mode [android13]

### ISSUE THREAD

**Issue by robovoice1** [mozilla/pontoon#2639]
![Screenshot_20221012-072128](https://user-images.githubusercontent.com/92784377/195259580-73e0847b-fb6d-4acf-a7ca-3e0158c3f439.png)

Google Pixel 6 pro
Android 13 GrapheneOS TP1A.221005.002.2022100300
Vandium Browser 106.0.5249.79

**Comment by mathjazz** [comment]
Thanks for the part. We'll take care of this as part of out broader effort to make Pontoon usable on mobile devices.

We track it under #2032.
