### ISSUE TITLE
Zabbix's Pontoon instace is very slow

### ISSUE THREAD

**Issue by yarons** [mozilla/pontoon#2640]
Attached is the memory map while the app is frozen:
https://share.firefox.dev/3CTzdzi

**Comment by Yur11** [comment]
Probably should open a ZBX ticket on https://support.zabbix.com, if this is still an issue.
I doubt that upstream developers will handle this.

**Comment by yarons** [comment]
It happens sure to excessive amount of strings, nothing to do with the backend, just frontend.

**Comment by mathjazz** [comment]
@yarons Could you provide a bit more details here?

On what pages is it slow (translate view, dashboards, everything)?

Any specific differences you see compared pontoon.mozilla.org in terms of the amount of projects, locales, files, strings...?

**Comment by Yur11** [comment]
Hi, @mathjazz, Zabbix team here.
Our installation was forked starting at 11e7c902c8bc24af84cc61a1a1d719dec0487045, which I presume was HEAD at the time. Made some minor changes.

Here are most of our changes except for changes in base.py, which are configuration changes and not logic.
https://gist.github.com/Yur11/e080571ff36009f25aa1dd600a83ffa5

**Comment by mathjazz** [comment]
Thank you for providing more clarity @Yur11 and @yarons!

From a quick look I wasn't able to experience any noticeable slowness in the translate view.

I would strongly suggest to update to the latest master and apply the patches there (some might even be interesting to be pulled upstream). Please reopen the ticket if the problem persists after the update.
