### ISSUE TITLE
Evaluate sync slowness for projects with project configuration

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2641]
We've noticed in projects with a lot of files that sync is very slow if the [project configuration](https://moz-l10n-config.readthedocs.io/en/latest/fileformat.html) is used vs. when it's not. One such example is https://pontoon.mozilla.org/projects/foundation-website-content/, where adding a new file triggered a several hours long sync job. We should investigate possible performance optimizations.

Since https://github.com/mozilla/pontoon/pull/1750 we also force-sync the project every time the configuration file changes. We should explore the possibilities of eliminating or minimizing the need for a force-sync.

**Comment by flodolo** [comment]
As a data point:
* I merged [this change](https://github.com/mozilla-l10n/www-l10n/pull/353/files) for mozilla.org (adding one file to Italian in mozilla.org).
* I think the [original sync in Pontoon](https://pontoon.mozilla.org/sync/log/289268/) timed out after 60 minutes. Another sync started [an hour later](https://pontoon.mozilla.org/sync/log/289274/).
* What's even more problematic is that the notification is triggered immediately, but Pontoon won't find the strings when you click the link. In this case, it took about an hour (sync was still going).
