### ISSUE TITLE
Multiversion string sync

### ISSUE THREAD

**Issue by yarons** [mozilla/pontoon#2646]
In Zabbix's Pontoon I'm seeing that when a string is updated for several versions it needs to be translated over and over again although it's the exact same string (I'm just completing it from the TM), is there a way to sync between versions so that the string will be automatically translated in all places and modified/propagated accordingly.

Thanks.

**Comment by mathjazz** [comment]
I don't understand what you mean by "updated for several versions".

**Comment by yarons** [comment]
In Zabbix there are multiple versions up for translation in parallel.
Is there a way to link those new strings?

**Comment by mathjazz** [comment]
So they are technically different strings (with different IDs), but have the same content?

What file format do you use?

**Comment by yarons** [comment]
@mathjazz Indeed.
It's gettext sadly.

**Comment by mathjazz** [comment]
Pontoon is just an editor for the PO file in this case, so I'm afraid there isn't much we can do here.
