### ISSUE TITLE
Contextual content preview

### ISSUE THREAD

**Issue by danielduckworth** [mozilla/pontoon#2658]
Hi, I've just come across this project and it looks excellent. I had a poke around the app in playground mode and I'm wondering if there is the facility to preview content (e.g., a front webpage or UI component) within the translation editor view?

**Comment by mathjazz** [comment]
The project actually started with in-context localization as its main feature, but later on changed course so much that the feature is not even available at the moment! 😐 

We track implementation of it in #2162.
