### ISSUE TITLE
Pre-translated Fluent string has the ID translated or modified

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2690]
It happened for at least two strings.

```
remember-pw-link = Remember your password? Sign in
```

Became

```
Remember-pw-link = Ricordi la password? Accedi
```

No clue why it changed to uppercase.

On the other hand, for 

```
plan-price-interval-year =
    { $intervalCount ->
        [one] { $amount } all’anno
       *[other] { $amount } ogni { $intervalCount } anni
    }
    .title =
        { $intervalCount ->
            [one] { $amount } all’anno
           *[other] { $amount } ogni { $intervalCount } anni
        }
```

The id was translated to `piano-prezzo-intervallo-anno`(but the translation was good besides that).

**Comment by mathjazz** [comment]
Was the string submitted as Error, Warning or Pretranslated?

I would expect the translation to be detected as an Error and skipped (not submitted at all).

**Comment by flodolo** [comment]
It was showing an error (I rejected one for Slovenian as well) and it was submitted as "pretranslated".

See the string getting removed from VCS after I removed it
https://github.com/mozilla/fxa-content-server-l10n/commit/c9f2ca744b7b78328fdc2c90e174741cc19c493b

**Comment by mathjazz** [comment]
OK, so the string was marked as Error in the dashboard, it had a Pretranslated (light green) Approve icon in the History panel and was committed to VCS.

The request here is to only machine-translate the part of the message that follows the ID, and make sure the ID remains unchanged.
