### ISSUE TITLE
Documentation on how to self-host

### ISSUE THREAD

**Issue by ImUrX** [mozilla/pontoon#2695]
I'm interested in self-hosting this but I have 0 experience with heroku, can anyone point me out in the right direction on where to look for the scripts used?

**Comment by mathjazz** [comment]
Perhaps these docs can help:
https://mozilla-pontoon.readthedocs.io/en/latest/dev/setup-virtualenv.html

For feedback, support, and 3rd party deployments, please check out [Discourse](https://discourse.mozilla.org/c/pontoon/).
