### ISSUE TITLE
How to download all project's translation resources in a single zip file?

### ISSUE THREAD

**Issue by Patriccollu** [mozilla/pontoon#2698]
Hello,

I'm **Corsican** [coordinator and translator](https://pontoon.mozilla.org/co/) for several Mozilla projects.

I'm no longer able to download all the translation files of a project in a single zip file. It looks to be a recent change on Pontoon because I was able to do that in last August.

I can still download a single translation file using "Download Translations" but this option is only at resource level, and no longer at project level; which isn't easy for projects such as Firefox for Android (35 resources) or Mozilla VPN (18 resources).

Did I miss something? Please can you shed some light on this?

Best regards,
Patriccollu.

**Comment by Patriccollu** [comment]
Here are some screenshots showing the available options displayed on the various project's pages.

Project page showing **all the resources** and options displayed on **Download** button:
![image](https://user-images.githubusercontent.com/22452654/210255324-71e88ffe-01f0-49c2-9498-a20201b76e66.png)

Project page showing **all the resources** and options displayed on **User** menu:
![image](https://user-images.githubusercontent.com/22452654/210255468-24749f88-41d8-433a-83db-8e18666b3b2c.png)

Resource page showing all the strings for **a specific resource** and options displayed on **User** menu:
![image](https://user-images.githubusercontent.com/22452654/210255644-d2140ea6-d62f-48b1-ae4a-8619e56f6757.png)

Project page showing all the strings for **all the resources** and options displayed on **User** menu:
![image](https://user-images.githubusercontent.com/22452654/210255701-f7c039ec-e677-4008-a52b-2a83a00e3b88.png)

And this is an extract of the **Documentation for Mozilla localizers** in Chapter [Downloading and uploading translations](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/translate.html#downloading-and-uploading-translations)

Anyone can download a terminology (.tbx), translation memory (.tmx) and translations, while only translators can upload translations. When downloading translations:

- The resource currently selected is downloaded in its original format, it’s not converted in any way.
- If the project contains more than 10 files, download is performed file-by-file. For larger projects a ZIP of all files is downloaded.

**Comment by mathjazz** [comment]
Sorry for the confusion, I just filed a PR to update the docs:
https://github.com/mozilla-l10n/localizer-documentation/pull/202

The correct statement is:
_If the project contains multiple files, a ZIP of all files is downloaded. If the project contains more than 10 files, download is performed file-by-file._

I know this sounds weird, but since Pontoon runs on ephemeral storage, it needs to download each file before processing it, which can get very slow in projects with 100s of files.

Feel free to file a separate bug to mitigate this issue.

**Comment by Patriccollu** [comment]
If that can help on similar requests, Bryan provided a work around in a [Localization topic on Discourse](https://discourse.mozilla.org/t/how-to-download-all-projects-translation-resources-in-a-single-zip-file/110029/2) to download a zip file from GitHub project's repository which will include all files for all locales.
