### ISSUE TITLE
Right-to-left punctuation not recognised as valid

### ISSUE THREAD

**Issue by bgo-eiu** [mozilla/pontoon#2699]
I am currently adding translations to the pa-PK locale, which uses an Arabic based script. If I translate a sentence line this:

Are you sure?

تسیں پکے او؟

I get a warning about missing punctuation even though a question mark is present.

Likewise, if a source message is like this:

Are you sure? Changes will not be saved.

تسیں پکے او؟ تبدیلیاں نہیں رکھےگا۔

I get a warning about the number of sentences not matching.

The characters to recognise are (not sure if any checks involve commas or semicolons:
* Period/full stop . = ۔
* Comma , = ،
* Question mark ? = ؟
* Semicolon ; = ؛
* Percentage sign % = ٪
* Per mille ‰ = ؉

Not every language written with the Arabic script uses the last two.

**Comment by mathjazz** [comment]
You might want to disable Translate Toolkit checks, which don't work too well in some scenarios, especially for some locales:
https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/translate.html#warnings
