### ISSUE TITLE
Static files seem to not pick up changes on local copy

### ISSUE THREAD

**Issue by Osmose** [mozilla/pontoon#27]
When I make changes to the static files on my local instance, it doesn't seem to pick them up. I suspect this has something to do with django-pipeline insisting on collecting static files (presumably because it thinks it needs to re-compile them on every request or something even though we're not using SASS or anything) and whatever mechanism is serving those static files is caching them when it shouldn't.

**Comment by mathjazz** [comment]
It works for me. I did update django-pipeline to the latest version, but I'm not sure if that had any impact on this.

**Comment by Osmose** [comment]
I don't think I've hit this in a while, we can reopen if it becomes an issue again.
