### ISSUE TITLE
Fluent: Translation rejected by string imported with an extra line break

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2710]
https://pontoon.mozilla.org/it/firefox-monitor-website/all-resources/?string=267702

I submitted a translation
https://github.com/mozilla/blurts-server/commit/0d87aa3f0ad876a2629ad2015687d4b8c35e7815

```
add-email-link = Aggiungi un indirizzo email
```

Then Pontoon proceeded to import the translation back with an extra line break, and rejecting the original translation.

**Comment by mathjazz** [comment]
This is a symptom of #2216, so essentially a dupe. I'll looking into it.

Note that fixing #2120 would also prevent this bug, but with the MessageFormat 2.0 transition, a fix for that bug is a little bit further away.
