### ISSUE TITLE
Google Translate not available in MACHINERY right after running pre-translation

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2718]
I've had issues in a couple of occasions with Google Translate not showing up for Italian in the MACHINERY tab.

The second time it was a few seconds after exposing new strings to Mozilla VPN (I believe [here](https://pontoon.mozilla.org/sync/log/252964/)). There were 2 strings, one was pre-translated, the other not (because it had a rejected suggestion).

When I opened the missing string, Google Translate wasn't there, I had to wait and reload the page. Given pre-translation just ran, the engine should have been available only a few seconds after.

**Comment by mathjazz** [comment]
We are now running the warmup job every minute, and sometimes (rarely, but) still hit a cold start.

We also hit a server error every now a few times per day (which is probably what triggered this bug):
```
google.api_core.exceptions.ServiceUnavailable: 503 The service is currently unavailable.
```

Sadly the QoS score seems pretty low.

There's only so much we can do here, so I'll close the issue.

Let's observe the behavior now that the warmup job runs at more predictable and frequent times and reopen this or file a separate issue if problem starts causing trouble again.
