### ISSUE TITLE
Translation area is prefilled with {""} for terms

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2737]
Example
https://pontoon.mozilla.org/mix/firefox-accounts/all-resources/?string=268239

The translation area shows `{ "" }`, although there are no matches whatsoever in MACHINERY.

**Comment by flodolo** [comment]
Turns out this was reported and fixed already in #2685? cc @eemeli

**Comment by eemeli** [comment]
It looks like the fix in #2685 only fixed this for messages, not terms. Because of course they're a little different.
