### ISSUE TITLE
Pontoon fails to approve string translation

### ISSUE THREAD

**Issue by petercpg** [mozilla/pontoon#2744]
Pontoon: https://pontoon.mozilla.org/zh-TW/sumo/all-resources/?string=263159
String repo: https://github.com/mozilla-l10n/sumo-l10n/blob/master/zh_TW/LC_MESSAGES/django.po#L3313-L3317

# STR
1. Open the string on Pontoon.
2. Submit and approve the translation (there's already one with 100% TM match)
3. Reload Pontoon page for the same string

# Expected 
The translation was saved and approved correctly

# Actual 
1. The string seems to be not approved in the translation area, however it is approved in the submission area.
1. By submitting the translation with the existing translation using Enter key, "Same translation already exist" displays every time.
2. By un-approving and approving the string again, the string seems to be approved. However refreshing the page the string became unapproved again.

**Comment by mathjazz** [comment]
I'd prefer data to be consistent, so 1.
