### ISSUE TITLE
Incomplete graphs in Insights tabs

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2749]
[This one](https://pontoon.mozilla.org/it/firefox/insights/) (Firefox, Italian) looks correct, but most graphs seem to be missing bars from all months with the exception of March 2022. Example: [VPN-Italian](https://pontoon.mozilla.org/it/mozilla-vpn-client/insights/), [VPN project](https://pontoon.mozilla.org/projects/mozilla-vpn-client/insights/).

**Comment by mathjazz** [comment]
We really need to fix that. See #2540.
