### ISSUE TITLE
Notifications pop-up uses different color schemes in different URLs

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2767]
https://pontoon.mozilla.org/nl/firefox/browser/browser/aboutLogins.ftl/?string=275207

<img width="424" alt="Screenshot 2023-02-21 alle 07 47 55" src="https://user-images.githubusercontent.com/3644868/220268492-ea8a3178-8c70-4c91-94be-a96aca5d83ad.png">

https://pontoon.mozilla.org/nl/

<img width="433" alt="Screenshot 2023-02-21 alle 07 48 02" src="https://user-images.githubusercontent.com/3644868/220268559-f1d04051-d6a4-46c0-b28a-283892782715.png">

**Comment by mathjazz** [comment]
See #2764.
