### ISSUE TITLE
Wrong email displayed in profile page

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2779]
https://pontoon.mozilla.org/contributors/U8WOfu_oDVhe1HzzXnGgncI1p0U/

<img width="287" alt="Screenshot 2023-03-03 alle 16 04 10" src="https://user-images.githubusercontent.com/3644868/222754325-5d5fc705-3d7a-408f-9954-6035332e76dc.png">

That's my email, not Rhoslyn's

**Comment by mathjazz** [comment]
Thanks, that was fixed in https://github.com/mozilla/pontoon/pull/2774.
