### ISSUE TITLE
Rejecting a pretranslated string doesn't remove them from repository

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2812]
https://pontoon.mozilla.org/zh-TW/mozillaorg/all-resources/?time=202304021244-202304021344&string=215305

I've rejected the strings with errors, then forced sync a couple of times for the project, but the strings are not removed. It's possible we never noticed because we normally submit an alternative?

**Comment by flodolo** [comment]
Looks like this is a different type of bug 🤔 

The strings was saved in Pontoon, and marked as an error. But it never made it to the repository with [the other strings](https://github.com/mozilla-l10n/www-l10n/commit/fc79bc3effa4eb07404291c1cc842ae984623fad), and that's why it wouldn't remove it.

Take for example [this string](https://pontoon.mozilla.org/zh-TW/mozillaorg/all-resources/?time=202304021244-202304021344&string=215305).

English

```
compare-edge-with-windows-10-microsoft-introduced-updated = With { -brand-name-windows } 10, { -brand-name-microsoft } introduced its { -brand-name-edge } browser to compete with { -brand-name-firefox } and { -brand-name-chrome }, making it the default browser pre-installed on millions of PCs sold. Even so, users were slow to adopt it and { -brand-name-microsoft } eventually announced plans to relaunch { -brand-name-edge } as a { -brand-name-chromium }-based browser ({ -brand-name-chromium } is { -brand-name-google }’s Open Source browser project). Since January of 2020, { -brand-name-microsoft }’s { -brand-name-chromium }-based { -brand-name-edge } has replaced the previous versions of { -brand-name-edge }. Although { -brand-name-edge } is now built on { -brand-name-google }’s { -brand-name-chromium }, a number of unique features do set it apart from { -brand-name-google }’s { -brand-name-chrome } browser.
```

```
compare-edge-with-windows-10-microsoft-introduced-updated = { -brand-name-microsoft } 在 { -brand-name-windows } 10 中推出了 { -brand-name-edge } 瀏覽器來與 { -brand-name-firefox } 及 { -brand-name-chrome } 競爭，使其成為已銷售的數百萬台電腦的預設瀏覽器。即便如此使用者們接受的速度還很慢{ -brand-name-microsoft } 最終還是宣布了將重新推出 { -brand-name-edge } 做為一套基於 { -brand-name-chromium } 技術的瀏覽器 { -brand-name -chromium } 是 { -brand-name-google } 的開放原始碼瀏覽器專案。自 2020 年 1 月起已經使用 { -brand-name-microsoft } 的 { -brand-name-chromium } 功能推出的 { -brand-name-edge } 取代了舊版的 { -brand-name-edge }。雖然 { -brand-name-edge } 現在是建立在 { -brand-name-google } 的 { -brand-name-chromium } 基礎上但也有許多與 { -brand-name-google } 不同的獨特功能的 { -brand-name-chrome } 瀏覽器。
```

BTW, the error is on `{ -brand-name -chromium }`.

The errors that I get from Pontoon trying to resubmit that translation are also extremely confusing (`Empty translations are not allowed`, when the translation is clearly not empty).

**Comment by mathjazz** [comment]
@flodolo, could you please confirm that my understanding of the bug(s) is correct?

1. The [said string](https://pontoon.mozilla.org/zh-TW/mozillaorg/all-resources/?string=215305) never made it to the repository along with other pretranslated strings. Which is not expected, because #2691 is not fixed yet.
2. Rejecting (other) pretranslated strings with errors (which made it to the repo) doesn't remove them therefrom?

**Comment by flodolo** [comment]
Point 1 is correct, this specific string never made it to the repository. I think this is happening only for Fluent errors.

For point 2 I'm not completely sure, but I believe it removed the strings that made it to the repository (e.g. Android).
https://github.com/mozilla-l10n/android-l10n/commit/1b8f223e53dced882c41ec4cc9c59ec15a233abe

**Comment by flodolo** [comment]
At this point, warnings/errors are never getting to the repository, so we don't need to investigate.
