### ISSUE TITLE
Machinery doesn't update for adjacent strings

### ISSUE THREAD

**Issue by nesnera** [mozilla/pontoon#2823]
When I find a string using a search, Machinery will offer its translation in the tab (using translation memory, MS Terminology, Google Translator although DeepL works better 😉). If I navigate between strings using the buttons (Alt+Up/Down shortcut), this does not happen. How do I force Machinery to activate?

**Comment by mathjazz** [comment]
Hey @nesnera! Whenever you open a string, Machinery should get updated.

Is it possible that you were not logged in?

**Comment by nesnera** [comment]
@mathjazz Thanks for the fix. 👍

**Comment by nesnera** [comment]
I'm sorry. It's still not behaving as I expected. Navigating and offering translation via Machinery between untranslated ones works fine. However, if I use navigation after manual search, Machinery no longer responds, see screen recording.

https://user-images.githubusercontent.com/1737463/236051998-77c28034-bc74-4972-8e84-beedc6ffb25a.mp4

**Comment by mathjazz** [comment]
I see. If you reveal adjacent strings and move to one of them (either by clicking directly or using navigation), Machinery doesn't update.
