### ISSUE TITLE
Capitalization and terminology inconsistency

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2824]
Filing as an issue, as it might be a good first-bug.

Also CC @bcolsson for visibility, since he'll need to review the doc at some point.

## Capitalization

While writing documentation for the profile settings page, I noticed a few capitalization inconsistencies. We're using sentence case for everything, except:
* Display Name
* Editor Settings
* Locale Settings

I think we should fix those to use sentence case.

## Misc

> If provided, used instead of login email address on the Profile page)

> Displayed on the public profile page

Get rid of "public" in the second. And capitalize Profile. And link Profile page to the Profile page like above.

> Logged in users

I think this should be `Logged-in users`
https://english.stackexchange.com/questions/10999/logged-in-log-ined-login-ed-logined-log-in-ed-logged-in

> ~Homepage locale~

~The default page is not a locale page, maybe this should just be called "Homepage"?~

**Comment by mathjazz** [comment]
Sentence case should also be used in:
- Translate Toolkit Checks
- Make Suggestions

**Comment by bcolsson** [comment]
Gravicon profile picture:

- Mouse over string should always be: "Update profile picture"
