### ISSUE TITLE
REQUEST CONTEXT or REPORT ISSUE is too slow

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2834]
On my machine and connection, it takes over 4 seconds for the name to appear. It looks broken to a normal user.

Looking at the network tab, it seems like we're fetching **all** the users (file is over 3MB)? That feels wrong.

We should prefetch the project manager for the current project, or maybe for all projects if we want to cover the "all projects" scenario.

**Comment by mathjazz** [comment]
See #2834.

**Comment by flodolo** [comment]
> See #2834.

You just pointed me to this very ticket ;-)

**Comment by flodolo** [comment]
(I suppose #2591 might be the one?)
