### ISSUE TITLE
Add space after mentions

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2840]
After inserting a mentioned user in the comment field, the cursor is positioned right after the user's name. 

We should also add space after mentions.

**Comment by eemeli** [comment]
The code attempts to do this already, but presumably this bit is somehow buggy? https://github.com/mozilla/pontoon/blob/570121addb91f7c618d247f27f3b844611a0fe69/translate/src/modules/comments/components/AddComment.tsx#L96-L98
