### ISSUE TITLE
Pretranslations of Android (strings.xml) strings containing straight quotes result in errors

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2858]
Android projects are another source of errors, because of unescaped quotes (we have 2 for Welsh)

_Originally posted by @flodolo in https://github.com/mozilla/pontoon/issues/2691#issuecomment-1497020066_

Currently, unescaped quotes in strings.xml strings are the only source of errors in non-Fluent projects. We should escape them or use curly quotes instead. See also: #2212.

**Comment by mathjazz** [comment]
Example:
https://pontoon.mozilla.org/cy/firefox-for-android/mozilla-mobile/fenix/app/src/main/res/values/strings.xml/?string=282921

**Comment by mathjazz** [comment]
Note that the translations with errors [don't get committed to VCS](https://github.com/mozilla/pontoon/pull/2816), as confirmed for the example above by the following two commits:
https://github.com/mozilla-l10n/android-l10n/commit/57b97ee684ef6673cb643bf28132b87018139b3c
https://github.com/mozilla-l10n/android-l10n/commit/7f108e37b256d73c86851bb7f3ab6ca2316862df

**Comment by mathjazz** [comment]
As the next step we should look into https://github.com/mozilla/compare-locales/blob/main/compare_locales/checks/android.py#L114 to understand how compare-locales checks work for quotes / apostrophes in strings.xml files.

A possible fix for this bug is to escape quotes / apostrophes on strings.xml pretranslations for which the aforementioned checks fail.

**Comment by flodolo** [comment]
Should we rename this, since it's not about pretranslation anymore, and more about improving user experience when submitting translations with straight quotes?

**Comment by mathjazz** [comment]
The general problem with Android quotes is already tracked in #2212. The proper solution is to do escaping behind the scenes, but it will require some time.

At the September 14 Pontoon call we've decided to try to approach the pretranslation-specific use case similarly to how we handle placeables in pretranslations (if checks fail, "do something").

**Comment by flodolo** [comment]
Just to make sure I understand: pretranslation might provide translation with straight quotes. That pretranslation is stored in Pontoon (and displayed as an error?) but not synced to VCS, so it doesn't impact build.

This is about "fixing" the pretranslation, e.g. interpolating it to remove the error?

**Comment by mathjazz** [comment]
> Just to make sure I understand: pretranslation might provide translation with straight quotes. That pretranslation is stored in Pontoon (and displayed as an error?) but not synced to VCS, so it doesn't impact build.

Correct.

> This is about "fixing" the pretranslation, e.g. interpolating it to remove the error?

Correct.

**Comment by mathjazz** [comment]
This issue was fixed as part of https://github.com/mozilla/pontoon/pull/3020, where we modified checks to not show errors on apostrophes and the serializer to escape them.
