### ISSUE TITLE
Can't type in editor with pending suggestion

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2880]
https://pontoon.mozilla.org/it/mozillaorg/en/products/vpn/platforms/android_v2.ftl/?string=281300

The string in question has a pending suggestion. If you click the editor, nothing happens.

If I move to a missing string, then back to the string in question, then I can edit it.

**Comment by flodolo** [comment]
Not sure what I did differently, but clicking that link now works as expected 🤔 

Leaving it open in case someone else can reproduce this.

**Comment by mathjazz** [comment]
@flodolo Seems like this is now also fixed?

https://mozilla-pontoon-staging.herokuapp.com/it/mozillaorg/en/products/vpn/platforms/android_v2.ftl/?string=281300

**Comment by flodolo** [comment]
I hope so. It was reproducing randomly even before, so hard to tell.
