### ISSUE TITLE
Translators can't approve pending suggestions

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2885]
I don't have more details, but we received reports from at least 2 locales (fy-NL, da) that they can't approve pending suggestions.

For those affected: it would be great if you could check the brower console and see if anything useful error shows up when you load the page, or when you try to approve a suggestion.

**Comment by Joergen** [comment]
I found this error in the Firefox console when the string https://pontoon.mozilla.org/da/firefox/dom/chrome/layout/css.properties/?status=unreviewed&string=280385 is loaded in Firefox:

```
XHRGET
https://pontoon.mozilla.org/microsoft-translator/?text=@property+syntax+descriptor+‘%S’+contains+components+without+a+pipe+between+them.&locale=da
[HTTP/1.1 400 Bad Request 231ms]

	
GET
	https://pontoon.mozilla.org/microsoft-translator/?text=@property syntax descriptor ‘%S’ contains components without a pipe between them.&locale=da
Status
400
Bad Request
VersionHTTP/1.1
Overført931 B (60 B størrelse)
Referrer-politik same-origin

    	
    Connection
    	keep-alive
    Content-Length
    	60
    Content-Security-Policy
    	script-src 'self' 'unsafe-eval' 'sha256-fDsgbzHC0sNuBdM4W91nXVccgFLwIDkl197QEca/Cl4=' 'sha256-G5/M3dBlZdlvno5Cibw42fbeLr2PTEGd1M909Z7vPZE=' https://www.google-analytics.com/analytics.js; frame-src https:; font-src 'self'; connect-src 'self' https://bugzilla.mozilla.org/rest/bug; worker-src https:; img-src 'self' https: data: https://*.wp.com/pontoon.mozilla.org/ https://www.google-analytics.com https://www.gravatar.com/avatar/; style-src 'self' 'unsafe-inline'; default-src 'none'
    Content-Type
    	application/json
    Date
    	Wed, 21 Jun 2023 06:27:12 GMT
    Referrer-Policy
    	same-origin
    Server
    	gunicorn/19.9.0
    Strict-Transport-Security
    	max-age=31536000
    Vary
    	Cookie
    Via
    	1.1 vegur
    X-Content-Type-Options
    	nosniff
    X-Frame-Options
    	DENY
    X-Xss-Protection
    	1; mode=block
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	da,en-US;q=0.5
    Cache-Control
    	no-cache
    Connection
    	keep-alive
    Cookie
    	heroku-session-affinity=AECDaANoA24IAeKFxvr///8HYgADw4BiAAC492EDbAAAAANtAAAABXdlYi4zbQAAAAV3ZWIuMm0AAAAFd2ViLjFqW/9n63p0xuQ2G8uvLsFfscYUwW8_; sessionid=vo48mvoplomw2ob0cuew795v8xd9qvth; _ga=GA1.2.1275390855.1687291543; _gid=GA1.2.1114563509.1687291543; _gat=1
    DNT
    	1
    Host
    	pontoon.mozilla.org
    Pragma
    	no-cache
    Referer
    	https://pontoon.mozilla.org/da/firefox/dom/chrome/layout/css.properties/?status=unreviewed&string=280385
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0
    x-requested-with
    	XMLHttpRequest
```
I found no errors when I try to approve the string.

**Comment by mathjazz** [comment]
This issue could be caused by recent changes in the editor (#2866) or it could be a duplicate of #2263.

@Joergen Do you get any visual feedback at all after you try to approve the translation? Do you see the progress bar on top of the page after the click? Do you get an error notification ("Oops, something went wrong")?

**Comment by Joergen** [comment]
> This issue could be caused by recent changes in the editor (#2866) or it could be a duplicate of #2263.
> 
> @Joergen Do you get any visual feedback at all after you try to approve the translation? Do you see the progress bar on top of the page after the click? Do you get an error notification ("Oops, something went wrong")?

When I click the Approve button I see the button txt "Approving" + the progress bar on top of the page moving to the right. I see no error messages.

**Comment by flodolo** [comment]
> This issue could be caused by recent changes in the editor (#2866) or it could be a duplicate of #2263.

Wouldn't we see the latter in the logs as a Python error?

**Comment by jakobkappel** [comment]
[pontoon_2885_2023-06-21 21-24-55.webm](https://github.com/mozilla/pontoon/assets/3586612/9ad0a353-cc3c-449d-8351-ef8e4303768c)

https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=281034

**Comment by flodolo** [comment]
> https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=281034

Exactly as it happened for fy-NL, I can approve this without any issue (I've unapproved it now), so it's something in the front-end, not in the DB.

**Comment by flodolo** [comment]
@jakobkappel 
Could you give it a try on a clean profile of Firefox? I'm wondering if an add-on could be interfering (I know I had the issue with the spellchecker).

**Comment by Joergen** [comment]
I have also tried to approve the string using an clean Firefox profile. It failed.

**Comment by flodolo** [comment]
I'm trying to set a temp account as translator for Danish, to see if that's a permission problem.

**Comment by flodolo** [comment]
I'm out of ideas:
* I tried downloading a Danish nightly of Firefox, create a new profile, and I can approve/unapprove the translation without problems.
* I even tried a VPN from Copenaghen, same result.

**Comment by mathjazz** [comment]
Only now I understand that this is a permanent issue (unlike #2880).

We'll revert the new editor until this is fixed.

**Comment by flodolo** [comment]
One more note is that I can't find Jakob or Jørgen in the action log, while I can find myself approving/unapproving that translation.

**Comment by jakobkappel** [comment]
> > We'll revert the new editor until this is fixed.
> 
> The changes have been reverted. Please let us know if you're now able to approve translations.

It works just fine with the string mentioned above (https://pontoon.mozilla.org/da/firefox-for-android/all-resources/?status=unreviewed&string=281034) :)

**Comment by Joergen** [comment]
I just approved a handful of strings for Firefox.

**Comment by mathjazz** [comment]
I wonder if this issue is specific for the big gree Approve button or was the behavior the same when using the Approve checkmark button.

**Comment by flodolo** [comment]
> I wonder if this issue is specific for the big green Approve button or was the behavior the same also when using the Approve checkmark button.

Both were working normally for me

**Comment by Joergen** [comment]
I only used the Approve button.

**Comment by mathjazz** [comment]
> I only used the Approve button.

Got another confirmation on Matrix that this only happens with the main Editor button (also used for Saving translations).

**Comment by mathjazz** [comment]
Might be related:
https://pontoon.mozilla.org/cs/firefox-relay-website/en/misc.ftl/?string=248079&utm_source=pontoon-addon
