### ISSUE TITLE
Can’t translate certain strings

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/pontoon#2887]
Hi,

I noticed that with certain strings, I can’t type in the translation field — clicking on the field does nothing. I’ve reproduced on both Nightly and Chrome.

<img width="993" alt="Capture d’écran 2023-06-21 à 13 17 45" src="https://github.com/mozilla/pontoon/assets/1294206/41f117cc-839c-4eb4-877b-4eb124580efc">

It happens here: https://pontoon.mozilla.org/fr/firefox-relay-add-on/all-resources/?string=281396

Here’s the error in the console:
<img width="731" alt="Capture d’écran 2023-06-21 à 13 17 29" src="https://github.com/mozilla/pontoon/assets/1294206/f35802fd-feee-4b7c-a613-1e857d516be1">

```
Content-Security-Policy : Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). single-file-extension-frames.js:1:294
Échec du chargement pour l’élément <script> dont la source est « https://www.google-analytics.com/analytics.js ». all-resources:1:1
XHRGET
https://pontoon.mozilla.org/microsoft-translator/?text=Unlimited+masks+now+available&locale=fr
[HTTP/1.1 400 Bad Request 444ms]

[@fluent/react] Error: The id "machinery-SystranTranslation--visit-systran" did not match any messages in the localization bundles. translate.min.e279c29abfea.js:26:136858
[@fluent/react] Error: The id "machinery-SystranTranslation--visit-systran" did not match any messages in the localization bundles. translate.min.e279c29abfea.js:26:136858
[@fluent/react] Error: The id "machinery-SystranTranslation--visit-systran" did not match any messages in the localization bundles. translate.min.e279c29abfea.js:26:136858
```

As a workaround, I’ve noticed selecting a different string then going back to the original string fixes the issue.

**Comment by mathjazz** [comment]
Thanks for the report, Théo! We're looking into the issue and tracking it under #2880.
