### ISSUE TITLE
Profile page should show if a user is not active

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2896]
A user can be disabled through Django Admin (uncheck `Permissions` -> `Active`), but currently there is nothing showing if a user is disabled when looking at their profile.

I think some sort of message should be displayed, potentially only visible to Administrators.

**Comment by mathjazz** [comment]
What is the use case for disabling an account?

Should we make the profile page of disabled accounts only visible to Administrators on top of making it clear the account is disabled?

**Comment by flodolo** [comment]
> What is the use case for disabling an account?

Abuse. We want to prevent the account from being created again (which will happen when we remove it).

> Should we make the profile page of disabled accounts only visible to Administrators on top of making it clear the account is disabled?

I think we should still show something, like "This account has been disabled by an administrator"?

**Comment by mathjazz** [comment]
> I think we should still show something, like "This account has been disabled by an administrator"?

To clarify: we'd show this to all users, not just admins?

**Comment by flodolo** [comment]
> To clarify: we'd show this to all users, not just admins?

Yes. I only see two alternatives:
* Display the profile as usual, with a warning seen only by Administrators.
* Display a message that the profile has been disabled, same for everybody.

We need to show something, because these users might have interacted with the UI (comments, suggestions, etc.), and the URL is somehow visible/reachable.
