### ISSUE TITLE
Ending newline mismatch error on GetText string 

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2897]
I was translating a GetText [string](https://pontoon.mozilla.org/it/firefox-accounts/all-resources/?search=By+proceeding,+you+agree+to%3A%3Cbr+%2F%3E&string=281483), and I couldn't approve a translation, because Pontoon would show a critical error

```
THE FOLLOWING CHECKS HAVE FAILED
    Ending newline mismatch
```

String

```

                By proceeding, you agree to:<br />
                Pocket’s <a class="link-grey" id="pocket-tos" href="https://getpocket.com/en/tos/">Terms of Service</a> and <a id="pocket-pp" class="link-grey" href="https://getpocket.com/en/privacy/">Privacy Notice</a><br />
                Firefox’s <a class="link-grey" id="fxa-tos" href="/legal/terms">Terms of Service</a> and <a class="link-grey" id="fxa-pp" href="/legal/privacy">Privacy Notice</a>.
              
```

I add to add an empty space on the last line, otherwise it wouldn't let me approve it. Where is this error coming from? Translate Toolkit was disabled, and it doesn't make any sense.

**Comment by flodolo** [comment]
Found the [source of the error](https://github.com/mozilla/pontoon/blob/8db9e9270d4b0e2e61e9b318ec1390a43e0bb33a/pontoon/checks/libraries/pontoon_db.py#L73C11-L77) 🤔

**Comment by mathjazz** [comment]
Seems like this error is expected:
https://www.gnu.org/software/gettext/FAQ.html#newline

I'm more curious if we can address the localizability issues in this string. Do we really need all the whitespace?

**Comment by flodolo** [comment]
This is a piece of FxA that is, hopefully, going to disappear soon. I don't think it's worth the effort to fix it.

What confuses me is that my translation had a new line at the end, but it needed an extra space, hence the resulting warning is very confusing. You can try to suggest a translation, just remove the space on the last line. 

Are we trimming too much?

**Comment by mathjazz** [comment]
The source string also has an empty space at the end, not the newline. If your translation ended with a newline, you had an ending newline mismatch, in which case the error message makes sense. There's no trimming involved.

**Comment by flodolo** [comment]
Thanks. I hate GetText more and more every day.
