### ISSUE TITLE
Microsoft Terminology API times out the gunicorn worker

### ISSUE THREAD

**Issue by ImUrX** [mozilla/pontoon#2899]
I was having issues with my 1 worker server, apparently pontoon stays waiting for Microsoft and it never answers at the end. Making gunicorn kill the worker used for it which was my only worker...

**Comment by mathjazz** [comment]
As of yesterday, Microsoft Terminology API seems to be shut down:
https://slator.com/microsoft-kills-off-beloved-language-portal/

I'll PR a patch to disable the service in Pontoon.
