### ISSUE TITLE
Pretranslation quality: likely incorrect data for Italian

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2944]
https://pontoon.mozilla.org/it/insights/

![canvas](https://github.com/mozilla/pontoon/assets/3644868/4950e65d-e2f2-4691-9909-bf76fbe5ed19)

I'm not aware of any pretranslation that required more than a couple of days, so not sure where this data for August comes from. Maybe a pretranslated string that was removed right away, and still shows up somewhere as pretranslated but not reviewed (because hidden in the UI)?

**Comment by mathjazz** [comment]
Found this:
https://pontoon.mozilla.org/it/firefox-accounts/payments.ftl/?string=279206

**Comment by mathjazz** [comment]
Looks like that pretranslation was initially approved (a day after), and got updated recently.

**Comment by mathjazz** [comment]
That would be one aspect of #2930.

**Comment by mathjazz** [comment]
I've manually fixed the bad value, the actual fix is to fix https://github.com/mozilla/pontoon/issues/2930.

I am now also looking into February data and will fix it accordingly if needed.
