### ISSUE TITLE
Impossible to edit the content in translate view (editor has contenteditable set to false)

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2955]
I believe it only happens when I click a notification from the Pontoon add-on, but I'm not 100% sure if that's the only case. This happens randomly, and I can't spot anything in the browser console to explain the issue.

This is a screenshot of the browser with DevTools showing how the editor has `contenteditable=false`. Setting it to true is also not enough (cursor appears, but still can't type).

<img width="1342" alt="editor" src="https://github.com/mozilla/pontoon/assets/3644868/c59084f0-6807-4bd9-a65e-af706d6289d9">

**Comment by flodolo** [comment]
Got the same this morning clicking a Transvision link, so it's not strictly related to the add-on.
The link in question was a search: https://pontoon.mozilla.org/hsb/firefox/browser/browser/shopping.ftl?search=powered-by-fakespot

**Comment by mathjazz** [comment]
Just hit the same issue with the following string:
https://pontoon.mozilla.org/sl/firefox-for-android/mozilla-mobile/android-components/components/feature/addons/src/main/res/values/strings.xml/?status=missing&string=285361

Got there from an internal page:
https://pontoon.mozilla.org/sl/firefox-for-android/

**Comment by eemeli** [comment]
I'll have a look at this over the next few days. First suspicion is that it's a timing issue with userinfo arriving a bit late and not producing an appropriate re-render of the editor.
