### ISSUE TITLE
Using the filter ‘Missing’ on Pontoon takes a long time.

### ISSUE THREAD

**Issue by Fjoerfoks** [mozilla/pontoon#2965]
I use https://pontoon.mozilla.org/fy-NL/all-projects/all-resources/?status=missing and https://pontoon.mozilla.org/nl/all-projects/all-resources/?status=missing to get to the latest missing strings in Pontoon. Since the last update loading of these results seems to have slowed down significantly.

**Comment by mathjazz** [comment]
The following view was also reported to be slower:
https://pontoon.mozilla.org/he/firefox/all-resources/?extra=missing-without-unreviewed&string=275204

**Comment by mathjazz** [comment]
It seems like response time of the `pontoon.base.entities` increased after we upgraded the DB from version 11 to 15.

<img width="1270" alt="Screenshot 2023-09-28 at 16 22 55" src="https://github.com/mozilla/pontoon/assets/626716/11b8eba4-12f2-4654-81f1-9f8cda47494f">

_Vertical lines represent deployments._
