### ISSUE TITLE
Warn on empty Fluent rich editor fields

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2977]
> In addition to the bug, I believe this is a UX regression? We should show a warning that one of the values is empty when trying to save such message.

The current practice is to consider any content in a Fluent value or attribute to qualify the whole message as not-empty. The check for this was added in #2675. Previously empty attributes may indeed have resulted in errors, due to stringifying as invalid Fluent.

_Originally posted by @eemeli in https://github.com/mozilla/pontoon/issues/2973#issuecomment-1750344569_

**Comment by flodolo** [comment]
Any chance to prioritize this? I just had to fix ~50 strings in one batch for Armenian, and my hope is that a warning would prevent most of these.

If you search for "empty" in [this page](https://test.flod.org/checks/), you will notice how frequent the problem is.
