### ISSUE TITLE
Rename Firefox accounts in Mozilla accounts

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2983]
There are a few references in the documentation, we should update them.
I think renaming internal references (e.g. fxa) goes beyond the scope, as most products will keep that for the time being.

We also need to make sure to update whatever package is responsible for the text in [this page](https://pontoon.mozilla.org/accounts/fxa/login/)

**Comment by mathjazz** [comment]
Opened a PR for the internal Pontoon codebase updates.

For the 2nd part, we should file an issue here:
https://github.com/pennersr/django-allauth
