### ISSUE TITLE
Bad placeable detection in the editor

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#2988]
Space and "d" are detected and highlighted as part of the placeable in the following string:
https://mozilla-pontoon-staging.herokuapp.com/sl/all-projects/all-resources/?string=66620

<img width="392" alt="Screenshot 2023-10-13 at 10 15 15" src="https://github.com/mozilla/pontoon/assets/626716/f17d9d4a-4f6b-4f12-bdec-7fad3238b4bc">

It's also interesting that the space following "%" is wider than the one preceding it.

**Comment by eemeli** [comment]
We can't really fix this without additional information on the format used in the .po file. In this case, `% d` is getting detected as a valid [Python printf](https://docs.python.org/3/library/stdtypes.html#old-string-formatting) expression for a signed integer with either a space ` ` or a dash `-` before the number, depending on its sign.

**Comment by mathjazz** [comment]
Replicating the behavior used in the source string would be good enough.

**Comment by eemeli** [comment]
Ah, this is actually a repeated instance of https://bugzilla.mozilla.org/show_bug.cgi?id=1251186 which was previously fixed with b9d056cd0.

So we should probably repeat that hack in the editor regexp.
