### ISSUE TITLE
Incorrect number of pretranslated strings in header for Italian

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2989]
The header says there are 2 pretranslated strings, but there are none at the moment. I wonder if it's counting hidden (obsolete) strings?

**Comment by mathjazz** [comment]
Looks OK to me:
https://pontoon.mozilla.org/it/mozilla-vpn-client/mozillavpn.xliff/?string=276710

**Comment by flodolo** [comment]
D'oh. I didn't realize I was hitting the problem with slow filters.
