### ISSUE TITLE
Hovering the notification bar makes it stick for over 10 seconds, with no way to dismiss it

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#3011]
Talking about the notification bar displayed after submitting a translation, or switching between suggest and translate mode.

If you hover the notification with your mouse, it will remain displayed and it's impossible to dismiss. 
It seems to disappear after about 10 seconds without user interaction.

**Comment by mathjazz** [comment]
That was supposed to be a feature. :) The idea is that you can read longer messages before they disappear. You should be able to close the notification bar by clicking on it.

I agree it's not really intuitive.

**Comment by flodolo** [comment]
I have no idea how I get into this state, but I'm still seeing very weird behavior with the bar. For example, this morning the notification sticks no matter where the cursor on my primary device.

**Comment by mathjazz** [comment]
I've been hitting this issue, too. Looking into it.
