### ISSUE TITLE
Suggestions with variables containing '*@' results in E-mail check failing

### ISSUE THREAD

**Issue by jakobkappel** [mozilla/pontoon#3012]
![billede](https://github.com/mozilla/pontoon/assets/3586612/eeee96aa-82ad-4c20-8c78-e621c53c2c93)

https://pontoon.mozilla.org/da/firefox-for-ios/all-resources/?status=missing&string=286540

**Comment by mathjazz** [comment]
Thanks for the report! Let's track this as part of the broader issue referenced above.
