### ISSUE TITLE
Cannot switch theme in Pontoon

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/pontoon#3039]
**STR:**
1. Sign in to https://pontoon.mozilla.org/.
2. Click the user avatar in top right corner.
3. Under _Choose appearance_, click either _Light_ or _System_.

**Expected behavior:**
- Pontoon theme changes to the selected one.

**Actual behavior:**
- A red error message briefly shows up with the following text `{"status": false, "message": "Bad Request: Invalid theme"}`, which is the response body of the `POST https://pontoon.mozilla.org/api/v1/user/{some ID}/theme/` HTTP call.

![obrazek](https://github.com/mozilla/pontoon/assets/3941344/7434b566-fe88-4ba1-b238-0dadaaf8879f)

**NOTE 1:** The message shows really brifly, so it took me a while to take the screenshot successfully. Although I understand it disappear rather quickly because it hides actionable parts of the UI, it's still quite fast to be able to read it.

**NOTE 2:** The error message in the UI should be something human readable, not a JSON.

**Comment by MikkCZ** [comment]
What I noticed now though is that the CSRF token included in that POST request is then used before in a previous POST to `https://pontoon.mozilla.org/log-ux-action/` (action type `Render:+Unread+notifications+icon`).

**Comment by mathjazz** [comment]
Thanks for digging into it! I'm still unable to reproduce the problem and we have about 100 users that are currently using the light theme or the system theme, so they must have been able to switch.

I was also able to change the theme for you via Django admin (I changed it back to the default value).

Are you able to change the theme in the translate view?

Would you be willing to review https://github.com/mozilla/pontoon/pull/3042?

**Comment by flodolo** [comment]
Looking at the differences with my own request, there are some additional fields

```
{
    "name": "Sec-GPC",
    "value": "1"
}

{
    "name": "Pragma",
    "value": "no-cache"
}

{
    "name": "Cache-Control",
    "value": "no-cache"
}
```

Not sure how useful this can be.

**Comment by MikkCZ** [comment]
It works for me now. Not sure what you did, @mathjazz. Could have been my profile was somehow "dirty" and it was not possible to load and save it, not related to the theme value?

**Comment by MikkCZ** [comment]
Well, I can still reproduce in staging. I did so now.

**Comment by MikkCZ** [comment]
In staging there is still the version that returns the error in the JSON response. I get
```json
{
  "status": false,
  "message": "User profile validation error: {'visibility_email': [\"Value 'Logged in users' is not a valid choice.\"]}"
}
```

**Comment by mathjazz** [comment]
We renamed the "Logged in users" `visibility_email` value to "Logged-in users":
https://github.com/mozilla/pontoon/commit/d8696c9deb54835272b6219ab97fd8a9c9f70802#diff-4ebc5e9888b2962aecd470dd76f7d410b4e246f2d8323df57ed7dd0c8d5e3adeL1678

But we didn't add a data migration to migrate users with the old value to the new one.

I'll add it to #3042.

**Comment by MikkCZ** [comment]
Sounds like it should have been an enum-like value that is decoupled between database, code, API and the UI. ;)

Anyway, this issue is fixed now, at least for me. Feel free to close it when you deem fit.

**Comment by mathjazz** [comment]
Yeah, the actual value (that gets stored) and the human-readable value are the same, which isn't ideal, as proven here. :)

Thank you for debugging, that error message on stage was the key.

I'll close the bug when we merge the PR. There are 27 other users with broken profiles, still. :)
