### ISSUE TITLE
Missing file in VPN project

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#3063]
I've exposed new strings for VPN, including 2 new files, and an update to an existing one.

For some reason, out of 2 new files, only one was picked up.

This is the file available in the `en` folder
https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/tree/main/en/addons/message_update_v2.20

The file is also available in other locale folders, but there's no trace of it in Pontoon.
https://pontoon.mozilla.org/de/mozilla-vpn-client/

`addons/message_whats_new_v2.20/strings.xliff` is showing up correctly.

**Comment by flodolo** [comment]
Manually changing the file seems to have triggered Pontoon sync
https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/commit/e015fdd67288ccdb3e9155b044da500c1b3ab34a

Still, far from ideal. I only noticed the file missing because I was setting up tags.

**Comment by flodolo** [comment]
From the log

```
 Jan 12 07:42:25 mozilla-pontoon app/worker.1 Changed files in Mozilla VPN Client repository and Pontoon, relevant for enabled locales: {'addons/message_whats_new_v2.20/strings.xliff': [], 'mozillavpn.xliff': []}
Jan 12 07:42:25 mozilla-pontoon app/worker.1 [2024-01-12 07:42:24,817: INFO/ForkPoolWorker-128] Changed files in Mozilla VPN Client repository and Pontoon, relevant for enabled locales: {'addons/message_whats_new_v2.20/strings.xliff': [], 'mozillavpn.xliff': []}
Jan 12 07:42:25 mozilla-pontoon app/worker.1 Relative paths in Mozilla VPN Client that need to be synced: dict_keys(['mozillavpn.xliff', 'addons/message_whats_new_v2.20/strings.xliff'])
```

But all files were exposed at the same time
https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/419

**Comment by mathjazz** [comment]
The file was moved, not added. So this is #2211.

As a consequence, we also hit #2057 - the old file is still exposed in Pontoon. Should we remove it? What about https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/tree/main/en/addons/message_update_v2.18?

**Comment by mathjazz** [comment]
> Where do you see the new file being the result of a move?

Here:
https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/commit/2a24ef26fa883121792ad6c8c165cc2010a0563f#diff-a1be6ee5e591c45d262359353d7ee71c67b9bc4f56583f8cd06678b25145b3f0

Check the icon and the filenames. Maybe git is being "smart"?

**Comment by flodolo** [comment]
Lovely, so git randomly decides that a file has been moved (notice how different locales are treated differently, it's new for `bg` but a move for `en`).

```
git diff --name-status 3eef2a4d700754ee0ba077fb29cf5ca807848bac..2a24ef26fa883121792ad6c8c165cc2010a0563f --name-status
D       bg/addons/message_update_v2.19/strings.xliff
A       bg/addons/message_update_v2.20/strings.xliff
A       bg/addons/message_whats_new_v2.20/strings.xliff
M       bg/mozillavpn.xliff
D       co/addons/message_update_v2.19/strings.xliff
A       co/addons/message_update_v2.20/strings.xliff
A       co/addons/message_whats_new_v2.20/strings.xliff
M       co/mozillavpn.xliff
D       cs/addons/message_update_v2.19/strings.xliff
A       cs/addons/message_update_v2.20/strings.xliff
A       cs/addons/message_whats_new_v2.20/strings.xliff
M       cs/mozillavpn.xliff
D       cy/addons/message_update_v2.19/strings.xliff
A       cy/addons/message_update_v2.20/strings.xliff
A       cy/addons/message_whats_new_v2.20/strings.xliff
M       cy/mozillavpn.xliff
D       da/addons/message_update_v2.19/strings.xliff
A       da/addons/message_update_v2.20/strings.xliff
A       da/addons/message_whats_new_v2.20/strings.xliff
M       da/mozillavpn.xliff
D       de/addons/message_update_v2.19/strings.xliff
A       de/addons/message_update_v2.20/strings.xliff
A       de/addons/message_whats_new_v2.20/strings.xliff
M       de/mozillavpn.xliff
R060    dsb/addons/message_update_v2.19/strings.xliff   dsb/addons/message_update_v2.20/strings.xliff
A       dsb/addons/message_whats_new_v2.20/strings.xliff
M       dsb/mozillavpn.xliff
D       el/addons/message_update_v2.19/strings.xliff
A       el/addons/message_update_v2.20/strings.xliff
A       el/addons/message_whats_new_v2.20/strings.xliff
M       el/mozillavpn.xliff
R067    en/addons/message_update_v2.19/strings.xliff    en/addons/message_update_v2.20/strings.xliff
A       en/addons/message_whats_new_v2.20/strings.xliff
M       en/mozillavpn.xliff
```

**Comment by flodolo** [comment]
https://stackoverflow.com/questions/433111/how-to-make-git-mark-a-deleted-and-a-new-file-as-a-file-move

🙄 

Unfortunately, I don't see a way to work around it in the automation, so it needs to wait for #2211.

Worth tracking it as part of the sync improvement initiative: how are we going to do that?

**Comment by mathjazz** [comment]
> Worth tracking it as part of the sync improvement initiative: how are we going to do that?

Add a milestone (1) to track this:
https://mozilla-hub.atlassian.net/wiki/spaces/FDPDT/pages/516391039/Localization+OKR+2024-H1#Improve-Pontoon-sync-reliability-(Q1-Q2)
