### ISSUE TITLE
Highlighting in sidebar's search results is misleading (capitalization is changed)

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#3096]
I'm searching for `verifica recensioni` because I want to replace it with `Verifica recensioni` (capitalized `V`): https://pontoon.mozilla.org/it/firefox-for-ios/all-resources/?search=%22verifica+recensioni%22&string=286496

The highlight in the sidebar changes the capitalization of the actual translation (using the search input), displaying it lowercase everywhere, which makes the sidebar quite useless.

**Comment by mathjazz** [comment]
See #3088.
