### ISSUE TITLE
Strings updated in INI file keep validated in pontoon

### ISSUE THREAD

**Issue by ddurieux** [mozilla/pontoon#3122]
In my reference ini file, I have for example: 
```
890_J_Mobi_Title=WIP - 890 Jump in danger
```
The string in translated and validated into pontoon.

It's normal ;)

When the reference ini file updated like:
```
890_J_Mobi_Title=danger for 890 Jump
```
and I sync, the string keep validated into pontoon and so the translation is wrong.
Is it possible to detect and put the string into not validated?

**Comment by nostrenz** [comment]
I notice this issue as well, so for example if I have a source language ini file containing the line:
```
890_J_Mobi_Title=WIP - 890 Jump in danger
```
I can add a validate a translation for that line, which works fine.

But, if I later load a newer version of the ini file where the content of that same line got changed to:
```
890_J_Mobi_Title=danger for 890 Jump
```
I would expect the translation added to that line to get automatically devalidated, so a translator can pick it up and translate it again. Sadly this is not the case, causing invalid translations to stay without translators being notified about it.

**Comment by mathjazz** [comment]
Thanks for the report!

Please note that Pontoon follows Mozilla's guidelines for [making changes to existing strings](https://mozilla-l10n.github.io/documentation/localization/making_string_changes.html). To sum up:

* If you are changing a string such that its meaning has changed, you must update the string ID.
* If your changes are relevant only for English — for example, to correct a typographical error or to make capitalization consistent — then there is generally no need to update the string ID.
