### ISSUE TITLE
Regularly purge unused database data

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#3135]
Purging unused Django session data reduced the Pontoon Stage DB size by almost 60%. From [Django docs](https://docs.djangoproject.com/en/dev/topics/http/sessions/#clearing-the-session-store):
> As users create new sessions on your website, session data can accumulate in your session store. When a user logs in, Django adds a row to the django_session database table. Django updates this row each time the session data changes. If the user logs out manually, Django deletes the row. But if the user does not log out, the row never gets deleted.
> 
> Django does not provide automatic purging of expired sessions. Therefore, it’s your job to purge expired sessions on a regular basis. Django provides a clean-up management command for this purpose: [clearsessions](https://docs.djangoproject.com/en/dev/ref/django-admin/#django-admin-clearsessions). It’s recommended to call this command on a regular basis, for example as a daily cron job.

Similarly, Pontoon sync logs data is one of the biggest table at the moment, only behind Translation, TranslationMemory and Insights tables. From [Pontoon docs](https://mozilla-pontoon.readthedocs.io/en/latest/admin/deployment.html#sync-log-retention):
> You may also optionally run the clear_old_sync_logs management command on a schedule to remove sync logs from the database that are over 90 days old.

We should:
- [x] Remove unused data from related tables.
- [x] [VACUUM](https://devcenter.heroku.com/articles/managing-vacuum-on-heroku-postgres) the related tables afterwards.
- [x] Set up cron jobs to do that regularly.

**Comment by flodolo** [comment]
> Purging unused Django session data reduced the Pontoon Stage DB size by almost 60%.

😱 Can we test locally how each of the steps affects the DB size?

**Comment by mathjazz** [comment]
I tested on stage. Total `django_session` table size (including indexes) is now 282 MB. It was 17 GB.

Just running `./manage.py clearsessions` didn't reduce the table size. I had to run VACUUM FULL.

**Comment by flodolo** [comment]
Sorry, I meant with a dump of the production DB. I assume we're going to run all the steps in automation, but I was curious which one has the largest impact (sessions, sync logs) on the current DB.

**Comment by mathjazz** [comment]
I restored the prod dump on stage beforehand. It was a few hours old when I ran the operations.

The DB size of the 3 SyncLog tables is about 1.7 GB:

```
                          table_name                          | table_size | indexes_size | total_size
--------------------------------------------------------------+------------+--------------+------------
 "public"."django_session"                                    | 11 GB      | 8267 MB      | 19 GB
 "public"."base_translation"                                  | 1371 MB    | 7459 MB      | 8830 MB
 "public"."base_translationmemoryentry"                       | 1202 MB    | 2200 MB      | 3403 MB
 "public"."insights_projectlocaleinsightssnapshot"            | 2473 MB    | 333 MB       | 2806 MB
 "public"."sync_projectsynclog"                               | 696 MB     | 726 MB       | 1423 MB
 "public"."notifications_notification"                        | 332 MB     | 862 MB       | 1194 MB
 "public"."actionlog_actionlog"                               | 259 MB     | 588 MB       | 847 MB
 "public"."insights_localeinsightssnapshot"                   | 291 MB     | 39 MB        | 330 MB
 "public"."sync_repositorysynclog"                            | 108 MB     | 123 MB       | 232 MB
 "public"."base_translatedresource"                           | 12 MB      | 165 MB       | 177 MB
 "public"."base_entity"                                       | 82 MB      | 54 MB        | 136 MB
 "public"."uxactionlog_uxactionlog"                           | 36 MB      | 5904 kB      | 42 MB
 "public"."sync_synclog"                                      | 13 MB      | 6880 kB      | 20 MB
```

**Comment by mathjazz** [comment]
Unused data has been removed and the cron jobs have been set up.

After a long time, [VACUUM FULL](https://devcenter.heroku.com/articles/managing-vacuum-on-heroku-postgres) has been performed on most tables. Total DB size dropped from 38 GB to 10 GB. The (compressed) DB dump is now just above 1 GB, down from almost 8 GB before the changes were made.

The Missing filter became noticeably faster after the changes were made. We should keep monitoring the [DB metrics](https://devcenter.heroku.com/articles/heroku-postgres-metrics-logs) for longer term trends.

**Comment by flodolo** [comment]
For posterity, could you provide a table similar to the one before the clean-up?

**Comment by mathjazz** [comment]
This is how the table sizes look now:

```
                          table_name                          | table_size | indexes_size | total_size
--------------------------------------------------------------+------------+--------------+------------
 "public"."base_translation"                                  | 1320 MB    | 2363 MB      | 3683 MB
 "public"."insights_projectlocaleinsightssnapshot"            | 3101 MB    | 179 MB       | 3279 MB
 "public"."base_translationmemoryentry"                       | 1196 MB    | 612 MB       | 1807 MB
 "public"."notifications_notification"                        | 327 MB     | 253 MB       | 581 MB
 "public"."actionlog_actionlog"                               | 257 MB     | 232 MB       | 489 MB
 "public"."django_session"                                    | 190 MB     | 109 MB       | 299 MB
 "public"."insights_localeinsightssnapshot"                   | 171 MB     | 10176 kB     | 181 MB
 "public"."base_entity"                                       | 65 MB      | 7224 kB      | 72 MB
 "public"."uxactionlog_uxactionlog"                           | 36 MB      | 5912 kB      | 42 MB
 "public"."sync_projectsynclog"                               | 27 MB      | 15 MB        | 41 MB
 "public"."base_translatedresource"                           | 10 MB      | 11 MB        | 21 MB
```

We might be able to reduce the total DB size by another 30% by fixing https://github.com/mozilla/pontoon/issues/2938.

**Comment by flodolo** [comment]
Interesting, looks like most table decreased between 40% and 60% in total size.

Looks like there are a couple of table missing from the new list (`public.sync_repositorysynclog`, `public.sync_synclog`)?
Also, what caused `insights_projectlocaleinsightssnapshot` to increase so much between the two samples?

**Comment by mathjazz** [comment]
In both lists, I only included tables with sizes expressed in MB.

```
                          table_name                          | table_size | indexes_size | total_size
--------------------------------------------------------------+------------+--------------+------------
 "public"."sync_repositorysynclog"                            | 2816 kB    | 2456 kB      | 5272 kB
 "public"."sync_synclog"                                      | 568 kB     | 304 kB       | 872 kB
```

Not sure what caused the increase in `insights_projectlocaleinsightssnapshot`.

**Comment by yoesak** [comment]
Hi accidentally delete all rows in django_session, and now I cannot open my pontoon site, how to restore it?
