### ISSUE TITLE
Increase cache hit rate

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#3142]
Our [table cache hit rate](https://devcenter.heroku.com/articles/heroku-postgres-metrics-logs) currently stands at 0.85 and is consistently below the recommended value of 0.99. In such case it is recommended to upgrade database plan for more RAM.

As per the [docs](https://devcenter.heroku.com/articles/understanding-postgres-data-caching), _the best way to understand what plan is best for your workload is to try them_. 

Our initial testing didn't show significant gains, but that could have been caused by [cold cache](https://help.heroku.com/BG4DPX6A/how-can-i-mitigate-a-cold-cache-in-postgres).

**Comment by mathjazz** [comment]
Upgraded plan on prod to Standard 2. Let's observe how that affects the cache hit rate and overall performance.

**Comment by flodolo** [comment]
Table cache hit rate seems to be constantly at 98%. Do we want to keep this open?

**Comment by mathjazz** [comment]
Let's close it. Bumping the plan clearly improved the hit rate and the next DB plan is much more expensive.

The best next step for further increasing the hit rate is probably #2938.
