### ISSUE TITLE
Drop docker/k8s-first-steps as unmaintained

### ISSUE THREAD

**Issue by eemeli** [mozilla/pontoon#3167]
We've not really done anything with Kubernetes/k8s since #1558 / #1580, leaving the `docker/k8s-first-steps` folder and its contents effectively unmaintained. We also have no current plans for doing anything with these.

For the sake of clarity, we should drop this from the repo as I'm not sure we've ever even tested if the example config works.

**Comment by RafaelJohn9** [comment]
hello @mathjazz, I would like to  be assigned this issue
