### ISSUE TITLE
Ability to log in a file

### ISSUE THREAD

**Issue by dag7dev** [mozilla/pontoon#3192]
It would be nice to have logs in a file, because right now log is managed just from console.

**Comment by RafaelJohn9** [comment]
@mathjazz can I work on this issue

**Comment by RafaelJohn9** [comment]
am  a new contributor to this repo, and I was looking for its active community too for support but I can't seem to find it.
![discourse](https://discourse.mozilla.org/c/pontoon/258/l) looks inactive for a while now

**Comment by mathjazz** [comment]
Hey @RafaelJohn9!

Sure thing, I've just assigned the issue to you!
