### ISSUE TITLE
LLM-Assisted translation feature roadmap/further developments

### ISSUE THREAD

**Issue by exsilium** [mozilla/pontoon#3198]
Hi, @ayanaar and @mathjazz - Firstly, great work from the entire team to land the LLM-Assisted feature, it's and exciting new capability to test and I'm so happy that in general there's no longer need to copy-paste text between Pontoon and OpenAI. Amazing work! 🥳 

As I was testing the feature I started to immediately want more from it and this issue is to get an understanding if there's a roadmap or plan how to enhance LLM capability going forward. Some questions I ran into while testing the feature:

1. Why is the AI rephrase/formality function limited to only Google translations and not included with Microsoft Translation machinery texts?
2. How can I give additional context to LLM on what is it that I'm actually translating or what kind of "theme" the text strings are referring to? This should most likely be a configurable option per project.
3. Would it be possible to pre-translate everything using AI, instead of rephrase'ing strings/paragraphs of texts one-by-one? I understand this goes perhaps beyond "assist" mode, but still, the quality for me seems to be superior to pure machine translations.

Cheers!

**Comment by ayanaar** [comment]
Hey @exsilium,

Thank you so much for your enthusiastic feedback and kind words! We're thrilled to hear you're enjoying the LLM-Assisted feature and finding it useful. Your input is invaluable as we continue to enhance this tool.

1. **Regarding your first question about extending the AI rephrase/formality function beyond Google translations:** That's an excellent suggestion. We've initiated issue #3203 to explore this further. We initially limited the feature to Google Translate to gather insights on usage patterns before considering broader integration. Your feedback helps us move in the right direction.

2. **On providing additional context to the LLM for translations:** We recognize the potential for this feature to greatly improve translation relevance and accuracy. However, implementing such capabilities raises concerns about possible misuse. We will explore ways to design this feature that both maximizes utility and minimizes the risk of abuse. Rest assured, your suggestion is on our radar.

3. **As for pre-translating entire texts using AI:** We appreciate your insights on the potential enhancements of moving from an "assist" mode to more comprehensive pre-translations. Our team is actively researching the effectiveness of LLM translations compared to trained machine translation models to better understand their respective strengths and limitations. According to our current research, LLM translations are not yet in a state to fully replace machine translations, but this is an area we are keen to develop further.

Cheers, and thanks again for your proactive engagement and suggestions. We're excited to keep improving this feature with your help!
