### ISSUE TITLE
Add ability to send messages to Pontoon users

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#3243]
This issue only tracks the implementation of the message editor and the ability to send its contents as a (transactional) email and/or an in-app notification.

An unsubscribe link is appended to messages as per the spec.

Spec:
https://github.com/mozilla/pontoon/blob/main/specs/0118-messaging-center.md#messaging-center

**Comment by bcolsson** [comment]
>An unsubscribe link is appended to messages as per the spec.

Non-transactional emails (i.e. emails that require opt-in consent): Should receive the unsubscribe link footer
Transactional emails: Should **not** receive the unsubscribe link footer (since users cannot opt-out of some transactional emails)
