### ISSUE TITLE
Add ability to see the Sent messages

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#3246]
Display a list of all previously sent emails or in-app messages from the Messaging Center.

Spec:
https://github.com/mozilla/pontoon/blob/main/specs/0118-messaging-center.md#review-past-message

**Comment by RafaelJohn9** [comment]
Hello @mathjazz  I would like to be assigned this issue

**Comment by mathjazz** [comment]
Hey @RafaelJohn9, sadly this issue is not ready yet, because we still need designs for it. Also, it's part of our team's plan for Q3, so we'd prefer to implement it ourselves.

Let me know if you need help picking another issue!

**Comment by RafaelJohn9** [comment]
Sure @mathjazz , which one has been bothering?
