### ISSUE TITLE
Unable to drag selected text to another location within the translated string

### ISSUE THREAD

**Issue by Fjoerfoks** [mozilla/pontoon#3249]
Previously it was possible to select text in the translation area and drag that text to another position within that string.
Can this feature come back?
I see this behavior here on Github too, with the difference that it is not only dragged to another spot, but also copied (which I think is weird btw).

**Comment by eemeli** [comment]
It looks like this should get fixed by updating our `@codemirror` npm dependencies. @harmitgoswami, would you be interested in taking a shot at this?

**Comment by harmitgoswami** [comment]
For sure!
