### ISSUE TITLE
[Mozilla instance] Emails sent from Pontoon to admins (e.g. project requests) are not delivered

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#3261]
Looks like we're sending the email to `team(at)pontoon.mozilla.com`, and that address doesn't exist, so we're currently not getting any request.

I noticed because I sent the request myself, so I got a copy, and then I got an error when replying

> Address not found
> Your message wasn't delivered to team(at)pontoon.mozilla.com because the domain pontoon.mozilla.com couldn't be found. 
> Check for typos or unnecessary spaces and try again.

**Comment by flodolo** [comment]
Checking with SRE, since that address should be an alias according to the original ticket.

**Comment by flodolo** [comment]
Temporarily changed `PROJECT_MANAGERS` to use the old address, at least we don't lose emails.

**Comment by flodolo** [comment]
Looks like the address is working now. Still, do we want to keep the current settings?

@mathjazz 
For when you're back next week.

**Comment by flodolo** [comment]
The `from` has been working from Pontoon, the `to` worked for me last week (and I got a `Is this thing on?` from you ~40 minutes ago).

**Comment by mathjazz** [comment]
Thanks for confirming. Looks like it missed my main Inbox (despite not hitting Spam). Found it now!

**Comment by mathjazz** [comment]
Changed `PROJECT_MANAGERS` back to `team(at)pontoon.mozilla.com` thanks to https://mozilla-hub.atlassian.net/browse/IO-2819.
