### ISSUE TITLE
GraphQL does not load

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#3292]
http://localhost:8000/graphql fails with a JS error.

**Comment by flodolo** [comment]
I assume this broke with #3183, which changed the inline script (and triggered CSP)?

**Comment by flodolo** [comment]
Note to future self, as it took me way too long to figure it out.

The main challenge is getting the right text to hash, as everything counts. The only way that worked for me was to inspect the page in DevTools, and copy the inner HTML within the `<script>`.

The hash itself is easy to calculate online ([example](https://report-uri.com/home/hash)) or offline

```
echo -n "
    window.GRAPHENE_SETTINGS = {
    
      graphiqlHeaderEditorEnabled: true,
      graphiqlShouldPersistHeaders: false,
      graphiqlInputValueDeprecation: false,
    };
  " | openssl dgst -sha256 -binary | openssl base64
```

The hash then needs to be added to `CSP_SCRIPT_SRC` for the DEV environment (`pontoon/settings/dev.py`).

**Comment by mathjazz** [comment]
Note that one of the browsers shows the hash as part of the CSP error message in the console.
