### ISSUE TITLE
Update curly regex for interpolations using double curly-brackets

### ISSUE THREAD

**Issue by flx-sta** [mozilla/pontoon#3327]
## Description

Hi,

I want to use pontoon self-hosted and I got it up an running.
I'm using the [i18next](https://www.i18next.com/) framework for translations and the problem is that the interpolation notation for this one is e.g. `Welcome to our Website, {{firstName}}`.

Translations are saved in JSON files

Pontoon recognizes this wrongfully as a `fluent` variable/placeable. and only highlights the `{{firstName}` part (missing the second closing curly bracket `}`).

I couldn't find anything about a setting to control this behavior (maybe deactivate the placeable/highlight feature) or something.

Any help/feedback is appreciated.

### Media

<img width="636" alt="image" src="https://github.com/user-attachments/assets/27913d69-8977-47c6-9c38-6b37c51abeff">
<img width="508" alt="image(1)" src="https://github.com/user-attachments/assets/fabe7b6b-91bf-4046-9aa6-5e550d800f76">

---

[Mozilla chat](https://matrix.to/#/!EqPuzyNlrbBGZiMvOm:mozilla.org/$cSRW9dWCiSvnQF6tqe4mWOtYOP6fuS2DY3AusPRLvNM?via=mozilla.org&via=matrix.org&via=delire.party)

**Comment by flx-sta** [comment]
Proposed new regex 
`{(?:(?:"[^"]*")|[^}])*}}?`
\- by *flood*
<img width="486" alt="image" src="https://github.com/user-attachments/assets/05eb0f1b-3dfc-403c-93cd-c34bfcdbc3a1">

**Comment by mathjazz** [comment]
Thanks for the report @flx-sta!

As mentioned on chat, we should update the [Highlighter](https://github.com/mozilla/pontoon/blob/main/translate/src/modules/placeable/components/Highlight.tsx#L16) regex to match these this type of placeables.

Since you already proposed a Regex, do you mind opening a PR?
