### ISSUE TITLE
String not found when searching for ID with both "search in string identifiers" and "search in translations only" enabled 

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#3344]
[Example for Firefox](https://pontoon.mozilla.org/it/firefox/browser/browser/aboutPrivateBrowsing.ftl/?search=about-private-browsing-focus-promo-text&search_identifiers=true&search_translations_only=true&string=243111): searching for `about-private-browsing-focus-promo-text` shows 3 results

That doesn't seem to work for Firefox for Android: I'm searching for `mozac_browser_errorpages_redirect_loop_message`
* If I enable the search in string identifiers, it works ([1 result](https://pontoon.mozilla.org/it/firefox-for-android/all-resources/?search=mozac_browser_errorpages_redirect_loop_message&search_identifiers=true&string=196837)).
* If I enable also the `search in translations only` option, it doesn't return [any result](https://pontoon.mozilla.org/it/firefox-for-android/all-resources/?search=mozac_browser_errorpages_redirect_loop_message&search_identifiers=true&search_translations_only=true).

Is this a bug or am I missing something obvious?

**Comment by flodolo** [comment]
It happens also with XLIFF (VPN, Firefox iOS).

**Comment by mathjazz** [comment]
The code is different for FTL and other formats.

Which of the two behaviors is expected? "Search in translations only" implies we don't search in string IDs.

**Comment by flodolo** [comment]
`Search in string identifies` means **includes** also string identifiers, not search **only** in string identifiers.
https://github.com/mozilla/pontoon/issues/3221

Firefox behavior is correct.

**Comment by mathjazz** [comment]
Sure, but Search in translations **only** excludes that? :)

Maybe we can also find a better wording?

**Comment by flodolo** [comment]
Yeah, I was thinking the same:

Maybe:
* Search in string identifiers ⇾ Include string identifiers
* Search in translations only ⇾ Exclude source content

**Comment by mathjazz** [comment]
>     Search in string identifiers ⇾ Include string identifiers
>     Search in translations only ⇾ Exclude reference content

Or rather than mixing Include/Exclude, we could do this:

`Search in translations only` ⇾ `Search in source strings` (enabled by default).

**Comment by mathjazz** [comment]
Or:

Search in:

- [ ] Source strings
- [ ] Translations
- [ ] String identifiers

**Comment by flodolo** [comment]
Wouldn't that create the same confusion you have about `Search in string identifiers`?

We could stick to one between Exclude/Include, my preference would be for the latter:
* `Include string identifiers` (default: disabled)
* `Include source strings` (default: enabled)

**Comment by mathjazz** [comment]
> Wouldn't that create the same confusion you have about `Search in string identifiers`?

Why? If `Search in source strings` is disabled it doesn't imply `Search in string identifiers` can't be enabled. Which is the problem

> UPDATE: As for the checkboxes, since we have other 2 "Match…" options, I'm not a fan of the idea.

I meant something like this:

![Posnetek zaslona 2024-09-17 ob 09 47 01](https://github.com/user-attachments/assets/8fca8c1a-a5de-4349-8efd-f02c30ec6579)

Or if we want to be 100% exact, we could even indicate that we're also searching in Translations and make that an option:

![Posnetek zaslona 2024-09-17 ob 09 59 48](https://github.com/user-attachments/assets/86f39fc4-61ff-4adf-81ca-9a7eb3e32cc6)

**Comment by flodolo** [comment]
> > Wouldn't that create the same confusion you have about `Search in string identifiers`?
> 
> Why? If `Search in source strings` is disabled it doesn't imply `Search in string identifiers` can't be enabled. Which is the problem

At the very start of this conversation you were not sure if `Search in string identifiers` was meant as "search only in", or "search also in". Why would `Search in source strings` be clearer in that regard?


> > UPDATE: As for the checkboxes, since we have other 2 "Match…" options, I'm not a fan of the idea.
> 
> I meant something like this:
> 
> ![Posnetek zaslona 2024-09-17 ob 09 47 01](https://private-user-images.githubusercontent.com/626716/368064591-8fca8c1a-a5de-4349-8efd-f02c30ec6579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjA1MTMsIm5iZiI6MTcyNjU2MDIxMywicGF0aCI6Ii82MjY3MTYvMzY4MDY0NTkxLThmY2E4YzFhLWE1ZGUtNDM0OS04ZWZkLWYwMmMzMGVjNjU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwODAzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjQzOTUzNDFjZWM4YmY2OWE0MDU2YTM2ZTMyMjlmYTI3MjJjMjE1Njk2ZGZmMmIzMjVhODE5ZmY5MmI5ZTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fRRNRphJnXIL3SZoeEdOpkdtvKzVrNMnqapMYIULXhc)

I like this approach, but I would use `Search also in:`, or `Include in the search:`. That avoids having to clarify further (2nd approach), which feels overkill.

**Comment by mathjazz** [comment]
> I like this approach, but I would use `Search also in:`, or `Include in the search:`. That avoids having to clarify further (2nd approach), which feels overkill.

Yup.

**Comment by mathjazz** [comment]
> At the very start of this conversation you were not sure if `Search in string identifiers` was meant as "search only in", or "search also in".

I don't think so? :) To me it always meant "Search also in". The problem I had was when the option was used together with another option, which explicitly says "Search only" in translations.

> Why would `Search in source strings` be clearer in that regard?

It's clearer than "Search in translation only" in that it doesn't exclude other options.

**Comment by mathjazz** [comment]
Filed #3345 to track search option changes.

Let's keep this one just about fixing the search behaviour in non-FTL strings when "Search in string identifiers" and "Search in translations only" are both enabled.
