### ISSUE TITLE
JSON: Pontoon doesn't remove key with sync from templates folder

### ISSUE THREAD

**Issue by VfanLee** [mozilla/pontoon#3373]
I deleted a lot of meaningless fields in the templates file. When I clicked Sync, they were indeed deleted in the templates, but the previous translations in other regions still exist. How can I delete them?

**Comment by flodolo** [comment]
Since you reference templates, I assume you're talking about gettext (.po) files? Propagating changes is really a job for [msgmerge](https://www.gnu.org/software/gettext/manual/html_node/msgmerge-Invocation.html).

Have you tried making a change in one of the locales and syncing again? Pontoon doesn't touch localized resources unless there an actual change in localization.

**Comment by VfanLee** [comment]
for example:

1. this is my template file：[个人作业_zh.json](https://github.com/ulearning-intl/ulearning-asia/blob/main/locales/templates/%E4%B8%AA%E4%BA%BA%E4%BD%9C%E4%B8%9A_zh.json)，I have deleted `m.UpAttachInfo1` field.
2. but in [pontoon ui](http://114.119.181.175:8000/en/asia_fix_0402/%E4%B8%AA%E4%BA%BA%E4%BD%9C%E4%B8%9A_zh.json/?search=m.UpAttachInfo1&string=92314), you can still see the `m.UpAttachInfo1` field.

I've already synced it.

**Comment by flodolo** [comment]
We don't use JSON internally (outside of webextensions), so I'm wondering if it's a problem with that specific format.

If you remove something from the source content, Pontoon will stop showing it in the UI after the sync is completed. `templates` is the content that would be picked as source based on [this code](https://github.com/mozilla/pontoon/blob/9a9c51686a739e332c6e31b4671d618804361c1a/pontoon/sync/vcs/project.py#L50C5-L57).

Do you see any error in the log, maybe referencing `json_keyvalue.py`?

**Comment by mathjazz** [comment]
> I deleted a lot of meaningless fields in the templates file. When I clicked Sync, they were indeed deleted in the templates, but the previous translations in other regions still exist. How can I delete them?

Hey @VfanLee, thanks for your report! Did you perhaps remove the strings from Pontoon?

Please note that Pontoon only supports managing (adding, removing, changing) source strings from the repository. I just tested a removal from a JSON file and it got removed from Pontoon as well:
https://github.com/mozilla-l10n/pontoon-test/commit/0332daf42bf27268f591c0242cf11c61bd83da30

**Comment by VfanLee** [comment]
OK, I tried again.

1. I tried a new file [tvet.json](https://github.com/ulearning-intl/ulearning-asia/commit/325883722f730c197be833e3d0b3341de93d8251) again. I deleted some fields. 
2. The deleted fields were indeed not displayed in [pontoon ui](http://114.119.181.175:8000/en/asia_fix_0402/tvet.json/?string=135685).
3. But the fields in locales(example: [en](https://github.com/ulearning-intl/ulearning-asia/blob/main/locales/en/tvet.json)) still existed.

**Comment by VfanLee** [comment]
> We don't use JSON internally (outside of webextensions), so I'm wondering if it's a problem with that specific format.
> 
> If you remove something from the source content, Pontoon will stop showing it in the UI after the sync is completed. `templates` is the content that would be picked as source based on [this code](https://github.com/mozilla/pontoon/blob/9a9c51686a739e332c6e31b4671d618804361c1a/pontoon/sync/vcs/project.py#L50C5-L57).
> 
> Do you see any error in the log, maybe referencing `json_keyvalue.py`?

I didn't find `json_keyvalue.py` in the server, maybe this is the reason?

![image](https://github.com/user-attachments/assets/8dbb5e0d-fd66-4c3b-a47a-8574f125a574)

**Comment by mathjazz** [comment]
@VfanLee Thanks for clarifying!

The removed strings don't get removed from locale files until you make a change in the locale for that specific file. Only that triggers sync. You can try that by changing one of the translations here (and then change it back): http://114.119.181.175:8000/en/asia_fix_0402/tvet.json/.

**Comment by VfanLee** [comment]
> @VfanLee Thanks for clarifying!@VfanLee 感谢您的澄清！
> 
> The removed strings don't get removed from locale files until you make a change in the locale for that specific file. Only that triggers sync. You can try that by changing one of the translations here (and then change it back): [http://114.119.181.175:8000/en/asia_fix_0402/tvet.json](http://114.119.181.175:8000/en/asia_fix_0402/tvet.json/).删除的字符串不会从区域设置文件中删除，直到您更改该特定文件的区域设置。只有这样才会触发同步。你可以通过更改此处的翻译之一（然后将其改回去）来尝试：http://114.119.181.175:8000/en/asia_fix_0402/tvet.json。

thanks, it's works!!!

**Comment by mathjazz** [comment]
Glad to hear! Closing.
