### ISSUE TITLE
how to delete user?

### ISSUE THREAD

**Issue by VfanLee** [mozilla/pontoon#3419]
Hello, I am using the Pontoon admin

I accidentally created a wrong user, so I deleted him, but a new "delete user" is generated every time I delete him. What happened? Why can't I delete him?

![image](https://github.com/user-attachments/assets/15c1abe1-8311-4b26-be9a-dbd0cfd46a08)

**Comment by flodolo** [comment]
That is by design if the user already had contributions or actions (those need to be attributed to a traceable user without personal information).
https://bugzilla.mozilla.org/show_bug.cgi?id=1561663#c6

**Comment by VfanLee** [comment]
Okay, I got it.
