### ISSUE TITLE
A newly registered user's email is not hidden

### ISSUE THREAD

**Issue by david-allison** [mozilla/pontoon#3429]
When a user registers a new account using Google:

* The `Display name` field is not set
* Email address privacy is set to `Translators`

But the email is leaked to anonymous users in the `<title>` tag of a user's profile via `contributor.name_or_email`

https://github.com/mozilla/pontoon/blob/5b4a3c111cdaf26313fe7e019e7384313e5ac89b/pontoon/contributors/templates/contributors/profile.html#L6

As a new user, I don't expect that my email is publicly visible by default.

Reproduction URL using throwaway email: https://pontoon.mozilla.org/contributors/ENetooEuEm76vy-GA4rhoIm34AI/

**Related** 
* https://github.com/mozilla/pontoon/issues/2407

**Note**
Your [terms of service](https://pontoon.mozilla.org/terms/) allows you to associate my email with my contributions, but I have not yet made any contributions.

**Comment by mathjazz** [comment]
Thanks for the report, @david-allison!

Profile URLs of users without any contributions are difficult to find, but we should still avoid exposing their email addresses publicly.

**Comment by janbrasna** [comment]
Question is whether such uses of `user_name_or_email` (=`self.first_name or self.email`) wouldn't generally be better as `user_display_name` (=`self.first_name or self.email.split("@")[0]`) that would turn any implicit `joepublic@example.net` into exposing just `joepublic`…
