### ISSUE TITLE
Can't approve translations in a private project

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#3447]
I've set up a new project: https://pontoon.mozilla.org/it/mozilla-vpn-extension

It's private, with only one locale (Italian). I've enabled pretranslation, and have the entire project waiting for review. When I try to approve translations, Pontoon gets stuck, and in the log I see

```
heroku/router at=info method=POST path="/translations/approve/" host=pontoon.mozilla.org request_id=d8184c45-fc8d-4c82-ad53-f1fbe3838029 fwd="216.9.110.2" dyno=web.3 connect=1ms service=2360ms status=500 bytes=5200 protocol=https
app/web.3     return self.__wrapped__.execute(sql, parameters,
app/web.3 psycopg2.errors.CheckViolation: new row for relation "base_locale" violates check constraint "base_locale_pretranslated_strings_3d164a91_check"
app/web.3 Traceback (most recent call last):
app/web.3   File "/app/.heroku/python/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
app/web.3     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app/web.3                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/web.3   File "/app/.heroku/python/lib/python3.11/site-packages/newrelic/hooks/framework_django.py", line 529, in wrapper
app/web.3     return wrapped(*args, **kwargs)
app/web.3            ^^^^^^^^^^^^^^^^^^^^^^^^
app/web.3   File "/app/pontoon/base/utils.py", line 139, in wrap
app/web.3            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/web.3   File "/app/.heroku/python/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
app/web.3     return view_func(request, *args, **kwargs)
app/web.3            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app/web.3   File "/app/.heroku/python/lib/python3.11/contextlib.py", line 81, in inner
app/web.3     return func(*args, **kwds)
app/web.3            ^^^^^^^^^^^^^^^^^^^
app/web.3   File "/app/pontoon/translations/views.py", line 309, in approve_translation
app/web.3     translation.approve(user)
app/web.3   File "/app/pontoon/base/models/translation.py", line 403, in approve
app/web.3   File "/app/pontoon/base/models/translation.py", line 350, in save
app/web.3     locale.adjust_stats(*args, **kwargs)
app/web.3     super().save(*args, **kwargs)
app/web.3   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
app/web.3   File "/app/.heroku/python/lib/python3.11/site-packages/django/db/models/base.py", line 990, in _save_table
```

**Comment by flodolo** [comment]
Note: I've disabled sync for the project, as I'm planning to translate it offline at this point.

**Comment by mathjazz** [comment]
> Digging deeper for the underlying issue.

Private projects are **EXCLUDED** from Locale stats when the project gets created:
https://github.com/mozilla/pontoon/blob/6948122e363e147448485efd8f99181ee297d712/pontoon/base/models/locale.py#L375-L385

When you add a new Private project, enable it for a locale with 0 pretranslations, and pretranslate all its strings, the Pretranslated count in the Locale dashboard will still be 0. (If you then make the project Public, the Locale stats will include the new project.)

When you try to approve a Pretranslation, different code is used to update stats for performance reasons. There, Private projects are **INCLUDED**:
https://github.com/mozilla/pontoon/blob/6948122e363e147448485efd8f99181ee297d712/pontoon/base/models/translated_resource.py#L156-L157

That means the Pretranslate value tries to gets set to -1, which is an IntegrityEror:

```
File "/app/pontoon/translations/views.py", line 309, in approve_translation
  translation.approve(user)
File "/app/pontoon/base/models/translation.py", line 403, in approve
  self.save()
File "/app/pontoon/base/models/translation.py", line 350, in save
  translatedresource.adjust_all_stats(**stats_diff)
File "/app/pontoon/base/models/translated_resource.py", line 157, in adjust_all_stats
  locale.adjust_stats(*args, **kwargs)
File "/app/pontoon/base/models/aggregated_stats.py", line 83, in adjust_stats
  self.save(
File "/app/pontoon/base/models/locale.py", line 446, in save
  super().save(*args, **kwargs)

...

django.db.utils.IntegrityError: new row for relation "base_locale" violates check constraint "base_locale_pretranslated_strings_3d164a91_check"
DETAIL:  Failing row contains (111, it, Italian, (n != 1), 1,5, <p>ITALIAN<br>
Questa sezione è gestita dal team di localizzaz..., 10744624, 99, 100, 54451, -1, 54462, 1, ltr, 69025000, Latin, default, it-it, it, 0, 11, it, , , NM902ca01a03289292, t).
```

In stats calucations, we should either special-case Private projects everywhere or nowhere.

This code might also need to be changed:
https://github.com/mozilla/pontoon/blob/6948122e363e147448485efd8f99181ee297d712/pontoon/base/models/translated_resource.py#L58

**Comment by flodolo** [comment]
This might be implicitly fixed in #3312? I remember @eemeli mentioning stats

**Comment by mathjazz** [comment]
> This might be implicitly fixed in #3312? I remember @eemeli mentioning stats

I'm afraid not - the inconsistency documented above is still there.

**Comment by mathjazz** [comment]
Obviously, the alternative to the above fix is to extend the special-casing of Public projects in Locale stats calculation to: https://github.com/mozilla/pontoon/blob/6948122e363e147448485efd8f99181ee297d712/pontoon/base/models/translated_resource.py#L156-L157

Ideally, we should show different stats to different users based on their permission, but that would make our already complex stats storage even more difficult to manage.

**Comment by eemeli** [comment]
> Ideally, we should show different stats to different users based on their permission, but that would make our already complex stats storage even more difficult to manage.

This becomes rather easy if we stop aggregating quite so much. For instance, if we were to drop the project & locale aggregated stats and only aggregate up to the projectlocale level, each project's visibility to the current user becomes much easier to express in a query.

As a workaround for the error, `adjust_stats()` could be adjusted to handle negative values differently, so that the updates with such are either skipped, or the counts floored to zero (as in `max(0, n)`).

**Comment by mathjazz** [comment]
> As a workaround for the error, `adjust_stats()` could be adjusted to handle negative values differently, so that the updates with such are either skipped, or the counts floored to zero (as in `max(0, n)`).

I worry this will just make errors in the code more difficult to spot.

I've updated #3451 with a fix that excludes private projects from Locale stats calculations also during the translation actions.
