### ISSUE TITLE
Incorrect desktop notification for awarded badge

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#3488]
I received the notification for an awarded badge, but the desktop notification (on macOS) said "Ignore"

<img width="765" alt="Screenshot 2024-12-13 alle 07 55 26" src="https://github.com/user-attachments/assets/ba92c333-a78d-454e-bc21-b6aa3a6979c7" />

**Comment by flodolo** [comment]
Now that I think of it, is this coming from the Pontoon add-on?

**Comment by mathjazz** [comment]
> Now that I think of it, is this coming from the Pontoon add-on?

Indeed, Pontoon isn't sending any push notifications.

This is how the notification looks in the Pontoon Add-On:
<img width="490" alt="Screenshot 2024-12-13 at 08 39 30" src="https://github.com/user-attachments/assets/a93fe662-ca58-4ef5-888d-316b0d91d62c" />

This is the culprit:
https://github.com/mozilla/pontoon/blob/5e90a8ac1ed8b5b6915156cf868534988b650cb3/pontoon/messaging/notifications.py#L14

**Comment by mathjazz** [comment]
https://github.com/MikkCZ/pontoon-addon/issues/975
