### ISSUE TITLE
Highlihgt the current opened file in the list

### ISSUE THREAD

**Issue by stenox** [mozilla/pontoon#36]
The following thing could improve Pontoon for localizers:
Remember current opened file or highlight it in the list, while next file is being selected. Especially for projects like Firefox OS, which have a lot of files.

![2015-06-22 09_41_07-pontoon - firefox developer edition](https://cloud.githubusercontent.com/assets/7978799/8276766/eb0d89b6-18c2-11e5-8755-7b7ca268aa80.png)

**Comment by mathjazz** [comment]
This has been fixed and has been backported to production, feel free to test it at:
https://pontoon.mozilla.org/

**Comment by stenox** [comment]
Now it doesn't work again...

**Comment by mathjazz** [comment]
Yeah, because we moved to a new server with slightly out of date codebase. The PR #42 is now merged and shall be deployed today, which means this functionality shall be re-enabled. Sorry for the confusion.
