### ISSUE TITLE
Separate commit by translator

### ISSUE THREAD

**Issue by stenox** [mozilla/pontoon#37]
The following thing could improve Pontoon for localizers:
Separate commit by translator, who made translation or modification. If more than one translator works at the same time, it would be good to push their work with separate commit for each translator.

**Comment by mathjazz** [comment]
To elaborate on that, we currently set commit author to the user who submitted the latest translation since last commit. To further improve the way we give credit to localizers in VCS, we should separate commits by user.

**Comment by Jobava** [comment]
It would be nice if the app remembered who contributed individual strings, though that may require tracking changes to a too fine granularity.

**Comment by mathjazz** [comment]
It already does that.

**Comment by Jobava** [comment]
Also, when the app commits to the L10n repos, it should also include a comment with the people that made contributions that round, space permitting.

**Comment by mathjazz** [comment]
Moved to Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1179213
