### ISSUE TITLE
Search strings

### ISSUE THREAD

**Issue by stenox** [mozilla/pontoon#38]
At the moment there is only one way to search strings on Pontoon: localizer could search only by opened file.
To meet better usability of localization process, Pontoon should have possibility to search strings by whole project.
![2015-06-22 09_47_58-pontoon - firefox developer edition](https://cloud.githubusercontent.com/assets/7978799/8276939/5967ab4c-18c5-11e5-87d3-802d3e8d5628.png)

**Comment by mathjazz** [comment]
This is one of the top priority issues, adding a link to the [Roadmap](https://github.com/mozilla/pontoon/wiki/Roadmap).

**Comment by mathjazz** [comment]
Moved to Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1178880
