### ISSUE TITLE
Pontoon frontpage renders Romanian letter Ț wrong

### ISSUE THREAD

**Issue by Jobava** [mozilla/pontoon#40]
It looks like the Romanian letter Ț is rendered wrong on the Pontoon frontpage, it's a little too large.

http://i.imgur.com/6cxDRSe.png

Another small issue is the comma sign below Ș is rendered differently from the same sign below Ț.

There are no other issues with the other Romanian letters.

**Comment by mathjazz** [comment]
Tracking this in Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1179017
