### ISSUE TITLE
New translated strings are replaced with old strings from hg

### ISSUE THREAD

**Issue by stenox** [mozilla/pontoon#41]
Not all translated strings are commited from Pontoon to hg.
Some strings on Pontoon are commited to hg (https://hg.mozilla.org/gaia-l10n/uk/rev/2aab07dcc006)
Some strings on Pontoon are replaced with old strings from hg (https://pontoon.mozilla.org/uk/firefox-os/shared/collection_categories/collection_categories.properties/)
I run into this issue from time to time...

**Comment by mathjazz** [comment]
There is a bug on file for this:
